### PR TITLE
fix(blog): correctly check if owner is a group in owner_block menu

### LINKED ISSUE #9972: blog ownerblock does not check for group entity when adding menu item

### PR DESCRIPTION
**Pull request by jdalsem**
fixes #9972

### CODE REVIEW

File: mod/blog/start.php [hunk 1]
```diff
@@ -178,15 +178,15 @@ function blog_set_url($hook, $type, $url, $params) {
...
-			$url = "blog/group/{$params['entity']->guid}/all";
-			$item = new ElggMenuItem('blog', elgg_echo('blog:group'), $url);
-			$return[] = $item;
+	$entity = elgg_extract('entity', $params);
+	if ($entity instanceof ElggUser) {
+		$url = "blog/owner/{$entity->username}";
+		$return[] = new ElggMenuItem('blog', elgg_echo('blog'), $url);
+
+	} elseif ($entity instanceof ElggGroup) {
+		if ($entity->blog_enable != "no") {
```
Comment (jeabakker) [inline mod/blog/start.php]: couldn't this line be combined in the previous if statement?
