### PR TITLE
fix(core): do not return false when appending a non existing file

### LINKED ISSUE #6949: ElggDiskFilestore::open('append') not working as expected
if I create a `new ElggFile()`, set `owner_guid` and `->setFilename("somename")` and then try `->open("append")` it fails.
Because of https://github.com/Elgg/Elgg/blob/1.9/engine/classes/ElggDiskFilestore.php#L63

I expected it to create the file if it didn't exist just like it suggests on https://github.com/Elgg/Elgg/blob/1.9/engine/classes/ElggDiskFilestore.php#L85

Maybe only `->open("read")` should fail if the file doesn't exist

### PR DESCRIPTION
**Pull request by jdalsem**
fixes #6949
- [x] change "open" to "read" on L71
- [x] change commit summary to "allows ElggFile to append files not yet existing"

### CODE REVIEW

**Comment by hypeJunction** [comment]
The commit message is not clear. I had to read it several times and only understood what is meant by looking at the code.
Can you give an example of what you are trying to fix here? I don't think I ever ran into an issue with this.

**Comment by jdalsem** [comment]
See the issue for details on the problem.

File: engine/classes/ElggDiskFilestore.php [hunk 1]
```diff
@@ -68,7 +68,7 @@ public function open(\ElggFile $file, $mode) {
 
 		$path = substr($fullname, 0, $ls);
 
-		if (($mode != 'write') && (!file_exists($fullname))) {
+		if (($mode === 'open') && (!file_exists($fullname))) {
```
Comment (hypeJunction) [inline engine/classes/ElggDiskFilestore.php]: `@param string    $mode read, write, or append.` 
Where does `open` come from? I think we should validate the modes first.

Comment (jdalsem) [inline engine/classes/ElggDiskFilestore.php]: Oops... it should be `read`... the validation is done  in the switch a few lines below

**Comment by mrclay** [comment]
better summary "allows ElggFile to append files not yet existing"
