### PR TITLE
fix(views): listing of entities and river no longer count if not needed

### LINKED ISSUE #11807: 2.3: elgg_list_entities prepares count even with pagination = false or limit = false
the count is ignored in elgg_view_entity list but still a useless query is executed during the preparation.

### PR DESCRIPTION
**Pull request by jdalsem**
fixes #11807

### CODE REVIEW

File: engine/lib/entities.php [hunk 1]
```diff
@@ -414,18 +414,27 @@ function elgg_list_entities(array $options = array(), $getter = 'elgg_get_entiti
...
-	$options['count'] = true;
-	$count = call_user_func($getter, $options);
-
-	if ($count > 0) {
-		$options['count'] = false;
-		$entities = call_user_func($getter, $options);
-	} else {
-		$entities = array();
+	$options['count'] = false;
+	$entities = call_user_func($getter, $options);
```
Comment (hypeJunction) [inline engine/lib/entities.php]: This can be `false`

Comment (hypeJunction) [reply engine/lib/entities.php]: Seems fine.
