### PR TITLE
fix(js): client-side hooks can now handle periods in hook names

### LINKED ISSUE #9160: Client-side hook/type names can't contain `.`
If the name has a period, an error is thrown. If the type has a period, the data matrix in `elgg.config.hooks` ends up containing misshapen data that I'm guessing is causing bugs we haven't found.

### PR DESCRIPTION
**Pull request by mrclay**
Previously, using a hook name with a period would fail, and using a hook type with a period would create an unexpected data structure within `elgg.config.hooks`.

This allows `elgg.provides()` to handle arbitrary names by giving them as an array, and uses this new API to handle hook names/types consistently.

Fixes #9160

### CODE REVIEW

File: js/tests/ElggHooksTest.js [hunk 1]
```diff
@@ -40,6 +40,18 @@ define(function(require) {
...
+			it("handles names/types with periods", function() {
+				expect(elgg.trigger_hook("fee.fum", "bar.bang")).toBe(null);
+
+				elgg.register_hook_handler("fee.fum", "bar.bang", function () { return 1; });
+
+				expect(elgg.trigger_hook("fee.fum", "bar.bang")).toBe(1);
+
+				elgg.register_hook_handler("fee.fum", "all", function () { return 2; });
+
+				expect(elgg.trigger_hook("fee.fum", "pow")).toBe(2);
```
Comment (mrclay) [inline js/tests/ElggHooksTest.js]: Ha! http://youtu.be/OmCupPRLWCw

**Comment by hypeJunction** [comment]
LGTM
