### PR TITLE
fix(entities): Entity creation no longer needlessly checks owner container

### LINKED ISSUE #4231: create_entity() calls can_write_to_container() on both owner and container (Trac #4231)
_Original ticket http://trac.elgg.org/ticket/4231 on 41973581-03-26 by trac user ismayil.khayredinov, assigned to unknown._

Elgg version: 1.8

The whole container permissions issues is starting to become a pain.

First of all, I don't understand why this check halts entity create in create_entity:

    	if (!can_write_to_container($user_guid, $owner_guid, $type, $subtype)) {
    		return false;
    	}

What does owner have to do with this???

Secondly, I think as we are moving to an ElggComment class, the entire can write to container will become a big pain. I think by default, any ElggObject should be able to serve as a container. ElggUsers and ElggGroups is a different thing, and I understand why the permissions checks are in place. With ElggObjects there is no reason to restrict writing to ElggObject container - this is in a way equivalent to canAnnotate().

### PR DESCRIPTION
**Pull request by mrclay**
BREAKING CHANGE:
When creating within a group, ElggEntity::create used to always separately check if the current user can use the owner's account as a container. This made sure that one group member could not post to the group using another member as owner. This separate check led to confusion, as handlers of the container_permissions_check hook were told that the owner was to be the container, when it was actually the group.

Here we bypass the separate owner container check if the desired owner_guid is the logged in user GUID. This eliminates the check under all normal circumstances but leaves it in place in case a poorly coded plugin allows the impersonation described above.

This also denies creation if the owner/container GUIDs are set but can't be loaded. Before, create() would simply bypass the permissions check if it couldn't load the owner/container.

Fixes #4231

(This is a modest change that eliminates the most common cases of #4231, but ultimately I think #8790 is the future)
- [x] log cases where return false
- [x] fix typo in docs

### CODE REVIEW

**Comment by mrclay** [comment]
Looks like we need a special case to allow an ElggSite to be created.

**Comment by mrclay** [comment]
In \ElggCoreObjectTest::testElggEntityRecursiveDisableWhenLoggedOut we explicitly test that objects can be created with owner/container = 0. Really?

**Comment by mrclay** [comment]
The owner->canEdit() check blocks creating messages, because we create them under the recipient's owner. So checking the owner might need to go completely.

**Comment by mrclay** [comment]
This latest version no longer calls canEdit() on the owner.

**Comment by beck24** [comment]
LGTM - I don't think this ever affected anything I've worked on, but this does make more sense

**Comment by juho-jaakkola** [comment]
I haven't dug that deep into this, but could this make it possible to post something as another user?

E.g. Juho and Steve are members of a group. Juho changes the owner_guid in the a creation form to the GUID of Steve. Steve is allowed to write to the group, so nothing blocks Juho from saving the post, and then it looks like Steve posted it.

**Comment by juho-jaakkola** [comment]
A highly unlikely scenario, though. And it would probably mean that the particular content plugin isn't very secure in the first place.

**Comment by mrclay** [comment]
Yes, that sounds right. So we can kind of think of posting in a group as posting to your own container as well. Really the case of creating content *owned by a different user* needs a separate permission & hook. I.e. check $owner->canUseAsOwner() with a separate hook.

Messages would need to be updated (sender creates with recipient as owner) and likely this wouldn't be BC. So maybe what we can get away with for now is something like https://github.com/mrclay/Elgg-leaf/commit/f83763efe4e4754b3bdb017ae3b6a9f2aff31a51 (from #8776)

**Comment by ewinslow** [comment]
What kind of testing do we need to do here to make sure this doesn't break discussions or something else?

**Comment by mrclay** [comment]
In case I wasn't clear, @juho-jaakkola's is right that, with this change, a very poorly designed plugin could allow one to post in a group impersonating another member's GUID as owner. I personally don't think that's worth worrying about, but our inability to really test this is a bigger problem.

The solution in #8776 is crude but also IMO almost risk-free. The urge to get 2.0 out make me lean that way.

**Comment by mrclay** [comment]
I'm a dummy. Solution is to verify owner container only if owner doesn't match logged in user. I'll update this later today and if there are no strong objections I'm just going to pull it in and finish off the associated changes to discussions.

**Comment by mrclay** [comment]
Alright, please take another look (updated description) if you have time.

**Comment by hypeJunction** [comment]
Seems correct.

**Comment by ewinslow** [comment]
Can you articulate the new intended behaviors in the form of test cases? Permissions code is the most sensitive part of the system. It may be worth it to do whatever refactoring is needed to get real tests in.

"Since this causes confusion" is vague. Can you be more specific about what goes wrong in the case you describe?

"Can write to the owner's container" seems wrong to me. Usually owners are users and don't have containers. Do you mean "can write to the owner as a container?" Maybe this is what causes confusion?

**Comment by ewinslow** [comment]
What kind of documentation updates are merited here? Worth adding simmering to the upgrade notes?

**Comment by benwerd** [comment]
Is there scope for maybe writing best practices about how plugin authors should retrieve and store owner GUIDs? Sticking them in the form - with or without further checking - is obviously a terrible (and lazy) idea, but it might not be obvious to everyone how to better go about it.

**Comment by mrclay** [comment]
@benwerd yeah, good idea. I've updated upgrade docs and the docs for the hook. Still considering what to do for testing.

**Comment by juho-jaakkola** [comment]
I'll take a closer look later tomorrow.

**Comment by juho-jaakkola** [comment]
LGTM

File: engine/classes/ElggEntity.php [hunk 1]
```diff
@@ -1524,18 +1524,28 @@ protected function create() {
...
 		}
 
-		$owner = $this->getOwnerEntity();
-		if ($owner && !$owner->canWriteToContainer(0, $type, $subtype)) {
-			return false;
+		// If given an owner, verify it can be loaded
+		if ($owner_guid) {
+			$owner = $this->getOwnerEntity();
+			if (!$owner) {
+				return false;
```
Comment (juho-jaakkola) [inline engine/classes/ElggEntity.php]: We should probably log each case when we return false.

```User <guid> tried to create <type> <subtype> in the entity <container_guid> but the container could not be loaded.```

File: docs/guides/upgrading.rst [hunk 2]
```diff
@@ -302,6 +302,13 @@ Comments plugin hook
 
 Plugins can now return an empty string from ``'comments',$entity_type`` hook in order to override the default comments component view. To force the default comments component, your plugin must return ``false``. If you were using empty strings to force the default comments view, you need to update your hook handlers to return ``false``.
 
+Container permissions hook
+--------------------------
+
+The behavior of the ``container_permissions_check`` hook has changed when an entity if first created: Before 2.0, the hook would be called twice if the entity's container was not the owner. On the first call, the entity's owner would be passed in as ``$params['container']``, which could confuse handlers.
```
Comment (juho-jaakkola) [inline docs/guides/upgrading.rst]: > when an entity if first created

should be:

> when an entity is being created

**Comment by juho-jaakkola** [comment]
@mrclay Can you make the changes so we can merge this?

**Comment by mrclay** [comment]
Changes made.
