### PR TITLE
fix(js): prevent multiple togglable menu item bindings

### LINKED ISSUE #9151: Keep track of registered toggleable menu items
We need to avoid duplicate registration of toggleable menu items. Event handlers are bound multiple times if called from multiple locations, so have to do this madness: https://github.com/hypeJunction/Elgg-actions_feature/blob/master/views/default/feature.js

### PR DESCRIPTION
**Pull request by hypeJunction**
elgg.ui.registerTogglableMenuItems() now clears previous click event bindings
to avoid multiple bindings if same items are registered by multiple plugins

Fixes #9151

### CODE REVIEW

File: js/lib/ui.js [hunk 1]
```diff
@@ -368,8 +368,10 @@ elgg.ui.initDatePicker = function() {
  * name is remove_friend, you should call this function with "remove-friend" instead.
  */
 elgg.ui.registerTogglableMenuItems = function(menuItemNameA, menuItemNameB) {
+
 	// Handles clicking the first button.
-	$(document).on('click', '.elgg-menu-item-' + menuItemNameA + ' a', function() {
+	$(document).off('click.togglable', '.elgg-menu-item-' + menuItemNameA + ' a')
```
Comment (mrclay) [inline js/lib/ui.js]: Why click.togglable? What fires this event?

Comment (hypeJunction) [inline js/lib/ui.js]: It's a namespaced event, which is triggered whenever `click` is triggered. You could also trigger it exclusively by `trigger('click.toggleable')`, or with all events in the namespace with `trigger('.toggleable')`.

Which makes me think perhaps using `on('elgg.ui.toggle')` in your other PR is not the safest pattern...

Comment (mrclay) [inline js/lib/ui.js]: OK yeah. Would you rather fix in 1.12? Up to you.

Comment (hypeJunction) [inline js/lib/ui.js]: Hm, not sure I can be bothered, and it will create merge conflicts.

**Comment by mrclay** [comment]
LGTM
