### PR TITLE
fix(views): in table lists, rows now have IDs

### LINKED ISSUE #10696: Table list type: rows need `elgg-object-` IDs
We can't use URL fragments with tables

### PR DESCRIPTION
**Pull request by mrclay**
Fixes #10696

### CODE REVIEW

File: views/default/page/components/table.php [hunk 1]
```diff
@@ -101,6 +102,7 @@
 	} else if (is_callable(array($item, 'getType'))) {
 		$type = $item->getType();
 
+		$row_attrs['id'] = "elgg-object-{$item->id}";
```
Comment (hypeJunction) [inline views/default/page/components/table.php]: Always object?

Comment (mrclay) [inline views/default/page/components/table.php]: Oops, I didn't even look how "list" did it. Should be fixed.

File: views/default/page/components/list.php [hunk 2]
```diff
@@ -69,8 +69,10 @@
 		if ($subtype) {
 			$li_attrs['class'][] = "elgg-item-$type-$subtype";
 		}
-	} else if (is_callable(array($item, 'getType'))) {
-		$li_attrs['id'] = "item-{$item->getType()}-{$item->id}";
+	} elseif (is_callable(array($item, 'getType'))) {
+		$type = $item->getType();
+
+		$li_attrs['id'] = "item-$type-{$item->id}";
```
Comment (mrclay) [inline views/default/page/components/list.php]: This is just to clean this up a bit and normalize with the table view.

**Review by hypeJunction — APPROVED** [review]
