### PR TITLE
fix(permissions): All permissions functions handle user fetches consistently

### LINKED ISSUE #8038: canEdit() allows invalid $user_guid argument
You can pass in GUIDs of non-users (e.g. 1), and it will function just fine, calling the plugin hook sending `user => (site object)`.

Also you can pass in a non-existent/deleted GUID and it will silently convert this to the session user.

In both cases I doubt we want to silently let this pass this through.

### LINKED ISSUE #8941: Allow (some) user lookups to find hidden/disabled users
When we added entity::canDelete() [we allow it to look up hidden/disabled users](https://github.com/Elgg/Elgg/commit/6b12e45db14e635a1fca450f441ca0ff0fae20f0#diff-8a29a646367211561f3d07149076efffR1088). It's odd we do this for canDelete, but not canEdit or others (AFAICT).

cc @jdalsem

### LINKED ISSUE #8945: WidgetsService::canEditLayout ignores passed in GUID checking admin
If you pass in a GUID, it only checks whether the *current user* is an admin (not the passed in user).
https://github.com/Elgg/Elgg/blob/2.x/engine/classes/Elgg/WidgetsService.php#L117

Could this be by design?

### PR DESCRIPTION
**Pull request by mrclay**
All permissions functions now find hidden/disabled users and, when a given GUID isn't found, they return false and issue a warning. Previously, only some functions issued warnings, and some functions would silently substitute the logged in user if a given GUID couldn't load.

Fixes #8941
Fixes #8038
Fixes #8945

### CODE REVIEW

File: engine/classes/ElggAnnotation.php [hunk 1]
```diff
@@ -120,27 +123,23 @@ public function enable() {
...
+
 		if ($user) {
 			// If the owner of annotation is the specified user, they can edit.
-			if ($this->getOwnerGUID() == $user_guid) {
+			if ($this->owner_guid == $user->guid) {
 				$result = true;
 			}
 
 			// If the user can edit the entity this is attached to, they can edit.
-			$entity = $this->getEntity();
```
Comment (mrclay) [inline engine/classes/ElggAnnotation.php]: I moved this line above the $user check so $entity is defined either way.

File: engine/classes/Elgg/WidgetsService.php [hunk 2]
```diff
@@ -108,17 +110,16 @@ public function createWidget($owner_guid, $handler, $context, $access_id = null)
...
-		if (!$user) {
-			$user = _elgg_services()->session->getLoggedInUser();
+		try {
+			$user = _elgg_services()->entityTable->getUserForPermissionsCheck($user_guid);
+		} catch (UserFetchFailureException $e) {
+			return false;
 		}
 
-		$return = false;
-		if (_elgg_services()->session->isAdminLoggedIn()) {
```
Comment (mrclay) [inline engine/classes/Elgg/WidgetsService.php]: I assume this was a bug (checking if the logged in user was admin, even if you pass in a different GUID).

File: engine/classes/Elgg/Database/EntityTable.php [hunk 3]
```diff
@@ -1235,4 +1265,31 @@ function updateLastAction($guid, $posted = null) {
...
+	 *
+	 * @param int $guid User GUID. Default is logged in user
+	 *
+	 * @return \ElggUser|false
+	 * @throws UserFetchFailureException
+	 * @access private
+	 */
+	public function getUserForPermissionsCheck($guid = 0) {
+		if (!$guid) {
+			return _elgg_services()->session->getLoggedInUser();
```
Comment (juho-jaakkola) [inline engine/classes/Elgg/Database/EntityTable.php]: I've been wondering whether we should start discouraging the use of permission checks without passing in the user. It would make checks safer (forces devs to think what exactly they're doing instead of relying on magic) and also would reduce the complexity of core (less stuff to inject).

This is just a hunch however. I'm not sure if it would also introduce problems.

File: engine/classes/Elgg/WidgetsService.php (hunk 2 above)
Comment (juho-jaakkola) [inline engine/classes/Elgg/WidgetsService.php]: Agreed

File: languages/en.php [hunk 4]
```diff
@@ -1287,7 +1289,7 @@
 	'entity:delete:success' => 'Entity %s has been deleted',
 	'entity:delete:fail' => 'Entity %s could not be deleted',
 	
-	'entity:can_delete:invaliduser' => 'Can not check canDelete for user_guid [%s] as the user does not exist.',
+	'entity:can_delete:invaliduser' => 'Cannot check canDelete for user_guid [%s] as the user does not exist.',
```
Comment (juho-jaakkola) [inline languages/en.php]: Let's change ```canDelete``` to ```canDelete()```. I remember someone assuming that it was some kind of a typo for "can delete".

File: engine/classes/Elgg/Database/EntityTable.php [hunk 5]
```diff
@@ -140,13 +141,16 @@ function rowToElggStar($row) {
...
+	 * @param string $type             Entity type. If given, even an existing entity with the given GUID
+	 *                                 will not be returned unless its type matches.
+	 * @param string $subtype          Entity subtype (use "" for default subtype). If given, even an existing
+	 *                                 entity with the given GUID will not be returned unless this matches.
+	 * @param bool   $ignore_condition If true, hidden/disabled entities may be found
 	 *
 	 * @return \ElggEntity The correct Elgg or custom object based upon entity type and subtype
 	 */
-	function get($guid, $type = '') {
+	function get($guid, $type = '', $subtype = null, $ignore_condition = false) {
```
Comment (juho-jaakkola) [inline engine/classes/Elgg/Database/EntityTable.php]: What's the use case for passing in type and subtype?

File: engine/classes/Elgg/Database/EntityTable.php (hunk 3 above)
Comment (beck24) [inline engine/classes/Elgg/Database/EntityTable.php]: I've been doing this with my own code for some time now for these exact reasons.  I'm starting to dislike the magic default of logged in user more and more as I work around edge cases.

Comment (juho-jaakkola) [inline engine/classes/Elgg/Database/EntityTable.php]: Anyway, thanks to this function we now have a good place to trigger the deprecation message, in case we later decide to deprecate the magic.

**Comment by juho-jaakkola** [comment]
The ```getUserForPermissionsCheck()``` is very nice idea!

File: engine/classes/Elgg/Database/EntityTable.php (hunk 3 above)
Comment (juho-jaakkola) [inline engine/classes/Elgg/Database/EntityTable.php]: Added a new issue #8953

File: engine/classes/Elgg/Database/EntityTable.php (hunk 5 above)
Comment (mrclay) [inline engine/classes/Elgg/Database/EntityTable.php]: @hypeJunction can you elaborate on the use case for this? I added it based on [your suggestion](https://github.com/Elgg/Elgg/pull/8942#discussion_r39630192), but I can't think of a good one.

Comment (mrclay) [inline engine/classes/Elgg/Database/EntityTable.php]: We allow passing in type for use in get_user() and loading the site entity.

Comment (hypeJunction) [inline engine/classes/Elgg/Database/EntityTable.php]: IMHO, it would server a shortcut to getting an entity of a specific type and subtype. Would eliminate the need to validate the subtype on an entity.

Comment (juho-jaakkola) [inline engine/classes/Elgg/Database/EntityTable.php]: Now I got it. That does sound like a nice feature!

File: engine/classes/Elgg/Database/EntityTable.php [hunk 6]
```diff
@@ -140,13 +141,16 @@ function rowToElggStar($row) {
...
 	 *
-	 * @param int    $guid The GUID of the entity
-	 * @param string $type The type of the entity. If given, even an existing entity with the given GUID
-	 *                     will not be returned unless its type matches.
+	 * @param int    $guid             Entity GUID
+	 * @param string $type             Entity type. If given, even an existing entity with the given GUID
+	 *                                 will not be returned unless its type matches.
+	 * @param string $subtype          Entity subtype (use "" for default subtype). If given, even an existing
+	 *                                 entity with the given GUID will not be returned unless this matches.
+	 * @param bool   $ignore_condition If true, hidden/disabled entities may be found
```
Comment (juho-jaakkola) [inline engine/classes/Elgg/Database/EntityTable.php]: I think ```$ignore_access``` would be better name because devs are already familiar with it.

**Comment by juho-jaakkola** [comment]
LGTM

File: engine/classes/Elgg/Database/EntityTable.php (hunk 6 above)
Comment (mrclay) [inline engine/classes/Elgg/Database/EntityTable.php]: True, but it does more, digging up disabled entities. Maybe two separate options?

File: engine/classes/Elgg/Database/EntityTable.php (hunk 5 above)
Comment (mrclay) [inline engine/classes/Elgg/Database/EntityTable.php]: How about, for this PR, we do the minimum for this refactoring and design this feature in another ticket?

Comment (juho-jaakkola) [inline engine/classes/Elgg/Database/EntityTable.php]: SGTM

File: engine/classes/Elgg/Database/EntityTable.php (hunk 6 above)
Comment (juho-jaakkola) [inline engine/classes/Elgg/Database/EntityTable.php]: Ah, true. I suppose the current name is fine.

**Comment by mrclay** [comment]
I've limited this to what's necessary to implement the fix.

**Comment by juho-jaakkola** [comment]
I believe this is safe to merge?
