### PR TITLE
fix(mysql): Use explicit ext/mysql resource in initial query/escaping

### LINKED ISSUE #8208: mysql_query used without explicit DB link passed in
In Elgg\Database::establishLink.

### PR DESCRIPTION
**Pull request by mrclay**
Fixes #8208

### CODE REVIEW

File: engine/classes/Elgg/Database.php [hunk 1]
```diff
@@ -642,6 +642,12 @@ public function sanitizeInt($value, $signed = true) {
 	 * @return string
 	 */
 	public function sanitizeString($value) {
+
+		// use resource if established, but don't open a connection to do it.
```
Comment (mrclay) [inline engine/classes/Elgg/Database.php]: My thinking here is that I don't want to change the timing of DB connections being made in the boot process. This may be overly paranoid.
