### PR TITLE
fix(file): better uploaded file handling and thumbnail serving

### LINKED ISSUE #6677: filestorename of files uploaded using file plugin are not kept updated
1. upload a file via the file plugin. (i am testing with video files - flv and mp4)
2. edit the elgg file object and upload a different file to the previously created file object.

examining the filestore directory, shows that the 2nd uploaded file is stored with the file name of the 1st file..
so if i upload xyz.flv and then replace it with xyz.mpg.. the file that is on the hard drive is still called xyz.flv even though it is an mpg.

besides that this is confusing when looking manually at the filestore - this may also cause problems when performing operations on filestore files - as i am currently, to generate video thumbnails.

### LINKED ISSUE #9267: File upload action - issues with replacing files
File upload action preserves the filename of the original file, when the file is being replaced. This has implications if the new file is of different type, as it may lead to wrong mimetype/simpletype detection, if for some reason browser fails to detect mime correctly, or a plugin is trying to detect mimetype, rather than relying on the metadata value.

Not sure what the correct approach to fixing is. Probably restricting replacements of files of the same type would be the least evil solution. I am not sure if replacing the name will affect anything.

### LINKED ISSUE #9612: File thumbnails sent with wrong Content-Type
Currently file thumbnails are generated as `jpeg`, but the thumbnail file extension and Content-Type sent is inherited from the source file.

The correct Content-Type is sent in 2.x (serve-file analyzes the file), but previous versions including 2.1 always send the original file's Content-Type.

We also should change the thumb file extensions to `jpg` for consistency, and in case the file is served elsewhere.

- [ ] wait for #9608 to be merged

### PR DESCRIPTION
**Pull request by mrclay**
Uploaded files now always have a new name with the client-given extension, even when replacing a previous upload.

Thumbnail JPEG files now have the `.jpg` extension and are served with the correct Content-Type. If a plugin happened to have created their own non-JPEG thumbs, they'd now be served with the correct MIME (instead of the original file's MIME type).

When an existing file is re-uploaded by a different user, the thumbnails are now created in the correct (owner's) directory.

If the file is recognized as an image, but thumbnails can't be created, we no longer allow thumbs from the previous file to be re-used.

Fixes #9612
Fixes #9267
Fixes #6677

### CODE REVIEW

File: mod/file/actions/file/upload.php [hunk 1]
```diff
@@ -108,61 +104,76 @@
...
-		$file->icontime = time();
-		
-		$thumbnail = get_resized_image_from_existing_file($file->getFilenameOnFilestore(), 60, 60, true);
-		if ($thumbnail) {
-			$thumb = new ElggFile();
-			$thumb->setMimeType($_FILES['upload']['type']);
+	$thumb = new ElggFile();
+	$thumb->owner_guid = $file->owner_guid;
+
+	$sizes = [
```
Comment (mrclay) [inline mod/file/actions/file/upload.php]: @hypeJunction thx :)

**Comment by hypeJunction** [comment]
LGTM.
I will rebase the other PR to avoid merge conflicts once this is in.

File: mod/file/actions/file/upload.php (hunk 1 above)
Comment (hypeJunction) [inline mod/file/actions/file/upload.php]: Welcome. One of the most annoying pieces of code in Elgg. Copy pasted way too many times.

**Comment by mrclay** [comment]
@juho-jaakkola are we OK with this much refactoring in 1.12? I figure it's worth it to fix 3 bugs.

**Comment by hypeJunction** [comment]
I don't think many will notice on 1.12. There is a dozen plugins all replacing the upload action.

**Comment by mrclay** [comment]
Manual testing: 
- uploaded new PNG image: thumbs are now .jpg
- replaced image with JPG image: file has new name
- replaced with XCF image (gimp): thumbs now removed.

File: mod/file/actions/file/upload.php [hunk 2]
```diff
@@ -108,61 +104,76 @@
 
 	$guid = $file->save();
 
-	// if image, we need to create thumbnails (this should be moved into a function)
-	if ($guid && $file->simpletype == "image") {
-		$file->icontime = time();
-		
-		$thumbnail = get_resized_image_from_existing_file($file->getFilenameOnFilestore(), 60, 60, true);
-		if ($thumbnail) {
-			$thumb = new ElggFile();
```
Comment (mrclay) [inline mod/file/actions/file/upload.php]: We didn't set the owner so we were assuming the logged in user owned it. Was this another bug?

Comment (hypeJunction) [inline mod/file/actions/file/upload.php]: :)

File: mod/file/actions/file/upload.php [hunk 3]
```diff
@@ -108,61 +104,76 @@
...
-			unset($thumblarge);
+			unset($image_bytes);
+
+			$file->{$data['metadata_name']} = $filename;
 		}
-	} elseif ($file->icontime) {
-		// if it is not an image, we do not need thumbnails
-		unset($file->icontime);
-		
-		$thumb = new ElggFile();
```
Comment (hypeJunction) [inline mod/file/actions/file/upload.php]: This is another one

**Comment by hypeJunction** [comment]
I am merging.
