### PR TITLE
fix(groups): respect previous modifications to the write access in group context

### LINKED ISSUE #8002: groups doesn't respect write access plugin hooks
the [groups_write_acl_plugin_hook](https://github.com/Elgg/Elgg/blob/1.9/mod/groups/start.php#L558) sets its own values and doesn't respect what other plugin hooks have already done.

use case:
 - A plugin hook unsets $return[ACCESS_PRIVATE]
 - In group contexts this get added again

### PR DESCRIPTION
**Pull request by jeabakker**
Remove all access write options based on the group content access level.
This will respect other plugins which have already removed access
options.

fixes #8002

### CODE REVIEW

File: mod/groups/start.php [hunk 1]
```diff
@@ -496,34 +496,45 @@ function groups_create_event_listener($event, $object_type, $object) {
  * Return the write access for the current group if the user has write access to it.
  */
 function groups_write_acl_plugin_hook($hook, $entity_type, $returnvalue, $params) {
-	$page_owner = elgg_get_page_owner_entity();
-	$user_guid = $params['user_id'];
+	
+	if (empty($params) || !is_array($params)) {
```
Comment (juho-jaakkola) [inline mod/groups/start.php]: Why do we need to check these? Core always passes in both user_id and site_id.

Comment (jeabakker) [inline mod/groups/start.php]: what if at some point core changes? what if someone triggers the same hook but forgot the params?

This will make more robust code, which core could definitely use

Comment (juho-jaakkola) [inline mod/groups/start.php]: Is it a good idea to silently stop executing the handler just because someone calls it the wrong way? After all the whole hook is useless if there is no user_guid whose permissions to check.

Comment (juho-jaakkola) [inline mod/groups/start.php]: Only use case I can think of is checking if ```$params['user_id'] === 0``` which means that for some reason the hook was called for an non-logged-in user.

Not passing any params seems like something that the developer should be notified about.

File: mod/groups/start.php [hunk 2]
```diff
@@ -496,34 +496,45 @@ function groups_create_event_listener($event, $object_type, $object) {
...
+	);
+	
+	if ($page_owner->getContentAccessMode() !== ElggGroup::CONTENT_ACCESS_MODE_MEMBERS_ONLY) {
+		$allowed_access[] = ACCESS_LOGGED_IN;
+		$allowed_access[] = ACCESS_PUBLIC;
+	}
+	
+	foreach ($returnvalue as $access_id => $access_string) {
+		if (!in_array($access_id, $allowed_access)) {
+			unset($returnvalue[$access_id]);
```
Comment (juho-jaakkola) [inline mod/groups/start.php]: This approach LGTM

File: mod/groups/start.php (hunk 1 above)
Comment (jeabakker) [inline mod/groups/start.php]: > Is it a good idea to silently stop executing the handler just because someone calls it the wrong way? After all the whole hook is useless if there is no user_guid whose permissions to check.

elgg_extract type hinting will trigger php warnings is not passed an array

> Only use case I can think of is checking if $params['user_id'] === 0 which means that for some reason the hook was called for an non-logged-in user.

this can trigger a php warning for unset array key

File: mod/groups/start.php [hunk 3]
```diff
@@ -496,34 +496,45 @@ function groups_create_event_listener($event, $object_type, $object) {
...
+	if (empty($params) || !is_array($params)) {
+		return $returnvalue;
+	}
+	
+	$user_guid = sanitise_int(elgg_extract('user_id', $params), false);
 	$user = get_user($user_guid);
-	if (!$user) {
+	if (empty($user)) {
 		return $returnvalue;
 	}
```
Comment (juho-jaakkola) [inline mod/groups/start.php]: Perhaps best would be to revert everything above this line for now, and discuss it in another issue/PR? I think the changes made below are good to merge.

Comment (jeabakker) [inline mod/groups/start.php]: Why, the internal handling of the function has not changed, it can just break 1 tiny step earlier which makes the code a little bit more robust.

Comment (juho-jaakkola) [inline mod/groups/start.php]: Because we're not unanimous about the stuff above. This prevents merging the stuff below.

**Comment by jeabakker** [comment]
reverted part of the change
