### PR TITLE
fix(river): custom joins can now reference default joined tables

### LINKED ISSUE #8580: custom JOINs are being added above core JOINS in elgg_get_entities_from_annotation_calculation?
as is documented in this community thread, when i provide a JOIN parameter to elgg_get_entities_from_annotation_calculation that references an alias that is created in the core code, an SQL error is thrown:

https://community.elgg.org/discussion/view/2223883/changing-the-sequence-of-where-clauses-in-elgg-get-entities-from-annotation-calculation

this appears to be because my join is being used in the final query above/before the core JOIN that contains the alias that i am referencing. as matt stated, the custom JOINs would be more appropriately added after the core JOINs.

### PR DESCRIPTION
**Pull request by propertunist**
When building more complex queries there may be a need to reference table aliases introduced by the default joins in _elgg_get_metastring_based_objects and elgg_get_river. This fix ensures that the default join table aliases are available when defining custom joins - which is a requirement for building effective and efficient queries.

Fixes #8580

### CODE REVIEW

**Comment by mrclay** [comment]
We still need to fix the commit message.
```
git commit --amend
```
In the editor, enter:
```
fix(river): custom joins are added after default joins

Optional joins are now added to river and metastring queries after default joins to allow default joins
to be referenced by optional joins.

When building more complex queries there may be a need to reference table aliases introduced
by the default joins in _elgg_get_metastring_based_objects and elgg_get_river. This fix ensures
that the default join table aliases are available when defining custom joins - which is a
requirement for building effective and efficient queries.

Fixes #8580
```
Exit, then force push the new commit:
```
git push -f
```

**Comment by propertunist** [comment]
ok, i see there is a 160 char limit per line.. i'll do it again

**Comment by propertunist** [comment]
not sure what the problem is this time... i can't see any clear description of the error on the travis page.

**Comment by mrclay** [comment]
Your editor is putting spaces before the `Fixes #8580`, but the real problem is this, mentioned in the Travis log:
```
FILE: /home/travis/build/Elgg/Elgg/engine/lib/river.php
--------------------------------------------------------------------------------
FOUND 2 ERROR(S) AFFECTING 2 LINE(S)
--------------------------------------------------------------------------------
 372 | ERROR | Tabs must be used to indent lines; spaces are not allowed
 373 | ERROR | Tabs must be used to indent lines; spaces are not allowed
```

File: engine/lib/river.php [hunk 1]
```diff
@@ -365,6 +369,9 @@ function elgg_get_river(array $options = array()) {
 		}
 	}
 
+ 	// add optional joins
```
Comment (mrclay) [inline engine/lib/river.php]: There's a single space before these tabs.

**Comment by mrclay** [comment]
Try hard to keep the commit summary under 100 chars, as we recommend in the docs. When you amend the commit, update the PR title to match the new summary.

**Comment by propertunist** [comment]
oh ok, so i need to view the raw log to find the issues. 
hmm.. there's definitely no space showing up in atom here on those lines.

**Comment by propertunist** [comment]
those lines do have a yellow line next to them (vertical) in atom.. is that to highlight that there is a problem? i know that atom is from the makers of github, so maybe they have included that level of integration? i have never seen that vertical line before.

**Comment by mrclay** [comment]
The lines indicate uncommitted modifications w/t/t git: https://discuss.atom.io/t/what-does-the-left-green-or-yellow-vetical-line-meaning/24471

**Comment by propertunist** [comment]
i see ok. i also see the errors in travis now without looking at the raw version.
i have no idea what to do with the tab problem as i am using a tab and not a space on those lines. the editor clearly shows that the spacing is that of a tab and not a space. maybe there's a configuration option i need to change in atom.. but this has not been a problem for any other lines that i have created in the same way. strangey!

**Comment by mrclay** [comment]
Fix the lines with another editor and file an Atom bug?

**Comment by mrclay** [comment]
Just to be sure, did you `git commit --amend` and `git push -f` after you made the last change?

**Comment by propertunist** [comment]
i just checked in netbeans 8.1 and the lines show a tab there too.
i did repeat the process of the amend and the the git push -f, yes.

**Comment by mrclay** [comment]
Does it have a "show whitespace" option? You can tell there's a leading space by just selecting the text in the diff.

File: engine/lib/river.php (hunk 1 above)
Comment (propertunist) [inline engine/lib/river.php]: how are the space characters denoted in github? i am not seeing them... these lines look exactly the same as all the other lines for me in github's diff view. they have a plus sign at the start and then just empty space up until where the text begins.

**Comment by propertunist** [comment]
there is a 'show invisibles' option, which i just enabled, but it made no difference to the output in the view area for the page. i just left you a line comment on the diff responding to your line comment. i don't see any spaces in the github diff either!

File: engine/lib/river.php (hunk 1 above)
Comment (mrclay) [inline engine/lib/river.php]: Select the whitespace at line 354 (one tab) then 372 (one space, one tab).

**Comment by propertunist** [comment]
i found the issue. there is an option in atom called 'soft tabs' and once i disabled it i could use proper tabs instead of auto-inserted space characters. so all tests have now passed.

**Comment by mrclay** [comment]
Spreading the commit summary across multiple lines means the changelog won't make sense. A concise version would be: `fix(river): river/metastring custom joins can now reference default joined tables`.

**Comment by propertunist** [comment]
ok, so shall i amend the commit and not push again this time?

**Comment by mrclay** [comment]
Amend and force push, yeah.

**Comment by propertunist** [comment]
ok, so that appears to be done, do i close this pull now?

File: engine/lib/river.php [hunk 2]
```diff
@@ -808,9 +815,9 @@ function _elgg_river_enable($event, $type, $entity) {
 	LEFT JOIN {$dbprefix}entities AS te ON te.guid = rv.target_guid
 	SET rv.enabled = 'yes'
 	WHERE (
-			(se.enabled = 'yes' OR se.guid IS NULL) AND 
+			(se.enabled = 'yes' OR se.guid IS NULL) AND
```
Comment (hypeJunction) [inline engine/lib/river.php]: Is this tested?  We might need these spaces

File: engine/lib/metastrings.php [hunk 3]
```diff
@@ -284,6 +279,14 @@ function _elgg_get_metastring_based_objects($options) {
 		$query = "SELECT {$options['metastring_calculation']}(v.string) as calculation FROM {$db_prefix}$type n_table";
 	}
 
+	foreach ($joins as $i => $join) {
+		if ($join === false) {
```
Comment (hypeJunction) [inline engine/lib/metastrings.php]: Any idea what this does and why we have it? Looks odd and not commented. Just asking.

**Comment by hypeJunction** [comment]
Looks ok, just hoping we are not breaking workarounds people might have implemented.  I did workaround this somewhere but can't remember which project now.

**Comment by beck24** [comment]
If it's a legit bug I don't think we can avoid breaking workarounds.  Bugs got to be fixed.

File: engine/lib/river.php (hunk 2 above)
Comment (propertunist) [inline engine/lib/river.php]: the space at the end of the line? that was removed by atom, the editor i am using. as far as i am aware, such spaces play no role in the parsing of SQL. i have tested these changes in the plugin i am coding that requires these changes to work and have not found any bugs or errors yet. the extent of my testing is not exhaustive, but i have also never seen any requirement for such spaces in SQL.

File: engine/lib/metastrings.php (hunk 3 above)
Comment (propertunist) [inline engine/lib/metastrings.php]: i don't know - i thought it was probably something thrown in there to fix something specific from a while ago. i don't know what exactly it would fix.

File: engine/lib/river.php (hunk 2 above)
Comment (beck24) [inline engine/lib/river.php]: That's fine, I don't think the spaces are necessary here, the line break should count as a space as it's not appending it as separate variables, it's all part of the same multi-line variable definition.  If it didn't break the SQL when you used it then we're good.

File: engine/lib/metastrings.php (hunk 3 above)
Comment (beck24) [inline engine/lib/metastrings.php]: I don't know the purpose of it, it's always been there.  I know I've used it as an undocumented feature to invalidate a query without hitting the database.
