### PR TITLE
fix(output): fewer view $vars will be output by accident

### LINKED ISSUE #8218: View vars leaking into markup
We need some stricter filtering of vars before formatting attributes. We end up with attributes such as ```entity_allows_comments="entity_allows_comments"```. Perhaps we could at least check for underscores in attribute names and filter those out.

### PR DESCRIPTION
**Pull request by mrclay**
A general problem is views passing along arbitrary $vars values to views like output/url, which treat unrecognized $vars as HTML attributes. This at least strips keys with underscores, which are definitely not meant to be HTML attributes.

Fixes #8218

### CODE REVIEW

File: engine/tests/phpunit/Elgg/lib/output/FormatAttributesTest.php [hunk 1]
```diff
@@ -0,0 +1,39 @@
+<?php
+namespace Elgg\lib\output;
```
Comment (mrclay) [inline engine/tests/phpunit/Elgg/lib/output/FormatAttributesTest.php]: This seemed like a decent namespace for lib tests.

**Comment by juho-jaakkola** [comment]
LGTM
