### PR TITLE
chore(plugins): Fixes path of discussions actions

### LINKED ISSUE #8640: master: "The action file for discussion/save was not found."
In start.php it's
```php
$action_base = elgg_get_plugins_path() . 'discussion/actions/discussion';
```
but it should be
```php
$action_base = elgg_get_plugins_path() . 'discussions/actions/discussion';
```

### PR DESCRIPTION
**Pull request by mrclay**
Also replaces most uses of elgg_get_plugins_path() with `__DIR__`.

Fixes #8640

### CODE REVIEW

File: docs/examples/plugins/start.php [hunk 1]
```diff
@@ -10,7 +10,7 @@ function my_plugin_init() {
 	// elgg_register_event_handler() call accordingly
 
 	// Register a script to handle (usually) a POST request (an action)
-	$base_dir = elgg_get_plugins_path() . 'my_plugin/actions/my_plugin';
+	$base_dir = __DIR__ . '/actions/my_plugin';
```
Comment (ewinslow) [inline docs/examples/plugins/start.php]: Thank you...

File: docs/tutorials/blog.rst [hunk 2]
```diff
@@ -287,12 +287,12 @@ page when the URL is set to ``/my_blog/all``. So, your new
...
         switch ($segments[0]) {
             case 'add':
-               include elgg_get_plugins_path() . 'my_blog/pages/my_blog/add.php';
+               include __DIR__ . '/pages/my_blog/add.php';
                break;
 
             case 'all':
             default:
-               include elgg_get_plugins_path() . 'my_blog/pages/my_blog/all.php';
+               include __DIR__ . '/pages/my_blog/all.php';
```
Comment (ewinslow) [inline docs/tutorials/blog.rst]: I thought we/I updated these to use elgg_view_resource... maybe that PR didn't get submitted yet...

File: mod/file/actions/file/download.php [hunk 3]
```diff
@@ -6,6 +6,6 @@
  */
 
 // @todo this is here for backwards compatibility (first version of embed plugin?)
-$download_page_handler = elgg_get_plugins_path() . 'file/download.php';
+$download_page_handler = dirname(dirname(__DIR__)) . '/download.php';
```
Comment (ewinslow) [inline mod/file/actions/file/download.php]: I'd like to see us register routes for this instead of putting files at magic locations on the filesystem... but that's a separate issue.

File: mod/messages/start.php [hunk 4]
```diff
@@ -58,7 +58,7 @@ function messages_init() {
 	elgg_register_plugin_hook_handler('container_permissions_check', 'object', 'messages_can_edit_container');
 
 	// Register actions
-	$action_path = elgg_get_plugins_path() . 'messages/actions/messages';
+	$action_path = __DIR__ . '/actions/messages';
```
Comment (ewinslow) [inline mod/messages/start.php]: Dropping elgg_get_plugins_path for `__DIR__` is such a small change but it feels soooo much cleaner. I can see why so many 3p plugins used `elgg_get_plugins_path`...
