### PR TITLE
Fixes 2 bugs relating to rel="toggle"

### LINKED ISSUE #7790: Navbar toggle does not work - 1.10

### LINKED ISSUE #7861: Site menu breaks on page loading
With responsive navigation, on page loading if you click on menu button page breaks.

image

I have tested it in my Elgg 1.8 & 1.9 installation and at Elgg community website (see sreenshot) with Aalborg theme enabled.

You can reproduce it refreshing the page and just clicking on the menu buttom. This issue is more evident with slow connection (like mobile internet connections)

### PR DESCRIPTION
**Pull request by mrclay**
fix(js): fixes aalborg site menu by restoring 1.9 toggle behavior.

We used to use the raw href attribute as the selector for rel=“toggle” elements, which supported hrefs like “.class-name”. In 1.10 we switched to using elgg.getSelectorFromUrlFragment(), which does not support this format, so we are switching back to maintain BC.

Fixes #7790

fix(ui): using site menu too early no longer results in 404 page.

Before elgg.ui.init binds events for toggles, the user may click the hamburger menu in aalborg, which was a link to a non-existent page. This repoints the link to “#” and sets the toggle selector via the new data- attribute.

Fixes #7861

### CODE REVIEW

**Comment by mrclay** [comment]
I can split this up if we really must

File: mod/aalborg_theme/views/default/page/elements/navbar.php [hunk 1]
```diff
@@ -9,7 +9,7 @@
 
 ?>
 
-<a class="elgg-button-nav" rel="toggle" href=".elgg-nav-collapse">
+<a class="elgg-button-nav" rel="toggle" data-toggle-selector=".elgg-nav-collapse" href="#">
```
Comment (mrclay) [inline mod/aalborg_theme/views/default/page/elements/navbar.php]: This would ideally be a button element, but in a bugfix release I'm not inclined to change it. cc @PerJensen @ewinslow

**Comment by beck24** [comment]
I wouldn't bother, LGTM

**Comment by juho-jaakkola** [comment]
LGTM

File: mod/aalborg_theme/views/default/page/elements/navbar.php (hunk 1 above)
Comment (ewinslow) [inline mod/aalborg_theme/views/default/page/elements/navbar.php]: +1 for `<button>` in future

Comment (mrclay) [inline mod/aalborg_theme/views/default/page/elements/navbar.php]: +1 for the future where `button` isn't a styling nightmare

**Comment by vikram06** [comment]
i was reported two issues..#7657 but elgg core team was ignore my name in elgg blog. 
http://blog.elgg.org/pg/blog/pawel/read/262/elgg-1102-released
what is wrong??

**Comment by jdalsem** [comment]
your name will only show up in the version history if there is a commit from your account. It is not related to reporting an issue.
