### PR TITLE
Register forward sent bug

### LINKED ISSUE #11217: master: not getting send to 'email sent' page after account registration

### PR DESCRIPTION
**Pull request by jdalsem**
Fixes #11217

### CODE REVIEW

File: mod/uservalidationbyemail/start.php [hunk 1]
```diff
@@ -103,20 +103,18 @@ function uservalidationbyemail_disable_new_user($hook, $type, $value, $params) {
...
  * Override the URL to be forwarded after registration
  *
- * @param string $hook
- * @param string $type
- * @param bool   $value
- * @param array  $params
+ * @param string                     $hook
+ * @param string                     $type
+ * @param \Elgg\Http\ResponseBuilder $value
+ * @param array                      $params
```
Comment (jeabakker) [inline mod/uservalidationbyemail/start.php]: the vars need a description, don't know why this passed PHPCS checks

**Review by jeabakker — DISMISSED** [review]
