### PR TITLE
fixed(notifications): listing of settings now contain a link to the item

### LINKED ISSUE #13123: notifications: list users alphabetically and make user name clickable

### PR DESCRIPTION
**Pull request by jdalsem**
fixes #13123

### CODE REVIEW

File: mod/notifications/views/default/notifications/subscriptions/record.php [hunk 1]
```diff
@@ -25,7 +25,10 @@
 	'alt' => $entity->getDisplayName(),
 ]);
 
-$name = $entity->getDisplayName();
+$name = elgg_view('output/url', [
+	'text' => $entity->getDisplayName(),
+	'value' => $entity->getURL(),
```
Comment (jeabakker) [inline mod/notifications/views/default/notifications/subscriptions/record.php]: `href` not `value` don't rely on magic
Maybe also add `'is_trusted' => true`

**Review by jeabakker — CHANGES_REQUESTED** [review]

File: mod/notifications/views/default/notifications/subscriptions/record.php (hunk 1 above)
Comment (jdalsem) [reply mod/notifications/views/default/notifications/subscriptions/record.php]: changed

**Review by jeabakker — APPROVED** [review]
