### PR TITLE
fix(comments): keep comment access_id in sync with container

### LINKED ISSUE #7807: Keep comment access_id in sync with container
Arck's solution would be better than nothing: https://github.com/arckinteractive/comment_access_sync. What it doesn't do (for practical reasons) is call events on the comments it updates.

### LINKED ISSUE #7984: WSOD when searching for "event calendar" on community site
It happens for the search string "event calendar" but not for the queries "event" or "calendar" or for example "event bla".

My guess is that the WSOD when search for "event calendar" might have something to do with the recent transfer of ownership of the Event calendar plugin and/or "Event calendar" group from Kevin to @juho-jaakkola. But maybe I'm wrong and the reason is something different. Regardless what the reason is I would say there should be a WSOD regardless whatever entered as search string.

### PR DESCRIPTION
**Pull request by beck24**
Fixes #7807, Fixes #7984
### Voting time

Yes let's pull this in:
- Matt
- Evan
- Brett
- Juho

Yes with more:
- Steve (show [UI message](https://github.com/Elgg/Elgg/issues/7807#issuecomment-82495268) when expanding access, don't close #7984)

No let's do something else:

### CODE REVIEW

**Comment by beck24** [comment]
Tested this manually by doing the following:

1. installing 1.x
2. create a blog post -> access public
3. create 2 comments -> check db -> they are access public
4. change blog post -> access logged in
5. check db -> comments still access public
6. switch to this branch -> run upgrade script
7. check db -> comments access logged in
8. run unit tests -> all pass
9. repeat steps 2-5 - comment access now syncs

**Comment by beck24** [comment]
Travis makes me sad :(
Anyone know what's up with that?

File: engine/classes/ElggEntity.php [hunk 1]
```diff
@@ -1686,7 +1686,14 @@ protected function update() {
 		unset($persisted_entity);
 
 		if ($allow_edit) {
-			$allow_edit = _elgg_services()->events->trigger('update', $this->type, $this);
+			$allow_edit = elgg_trigger_before_event('update', $this->type, $this);
```
Comment (hypeJunction) [inline engine/classes/ElggEntity.php]: Why not use _elgg_services()?

Comment (hypeJunction) [inline engine/classes/ElggEntity.php]: Not sure these changes belong in this commit. It will be a major pain point for plugin upgrades and should have it's own entry in the logs.

File: engine/lib/comments.php [hunk 2]
```diff
@@ -290,6 +292,57 @@ function _elgg_comments_notification_email_subject($hook, $type, $returnvalue, $
...
 
+/**
+ * Update comment access to match that of the container
+ * 
+ * @param string     $event  'update:after'
+ * @param string     $type   'all'
+ * @param ElggEntity $entity The updated entity
+ */
+function _elgg_comments_access_sync($event, $type, $entity) {
+	if ($entity instanceof ElggEntity) {
```
Comment (hypeJunction) [inline engine/lib/comments.php]: \ElggEntity

File: engine/lib/comments.php [hunk 3]
```diff
@@ -290,6 +292,57 @@ function _elgg_comments_notification_email_subject($hook, $type, $returnvalue, $
...
+		$options = array(
+			'type' => 'object',
+			'subtype' => 'comment',
+			'container_guid' => $entity->getGUID(),
+			'wheres' => array(
+				"e.access_id != {$entity->access_id}"
+			),
+			'limit' => false,
+		);
+		$batch = new ElggBatch('elgg_get_entities', $options);
```
Comment (hypeJunction) [inline engine/lib/comments.php]: \ElggBatch

File: engine/lib/comments.php [hunk 4]
```diff
@@ -290,6 +292,57 @@ function _elgg_comments_notification_email_subject($hook, $type, $returnvalue, $
...
+		// and to ensure write permissions
+		$ia = elgg_set_ignore_access(true);
+		$options = array(
+			'type' => 'object',
+			'subtype' => 'comment',
+			'container_guid' => $entity->getGUID(),
+			'wheres' => array(
+				"e.access_id != {$entity->access_id}"
+			),
+			'limit' => false,
```
Comment (hypeJunction) [inline engine/lib/comments.php]: I think the convention is 0

File: engine/lib/comments.php (hunk 3 above)
Comment (hypeJunction) [inline engine/lib/comments.php]: Do we need to set increment offset to false?

File: engine/lib/upgrades/2015031300-1.11.0_dev-comment-access-sync-50c9764e5845315c.php [hunk 5]
```diff
@@ -0,0 +1,42 @@
...
+
+if (elgg_get_entities($options)) {
+	$path = "admin/upgrades/commentaccess";
+	$upgrade = new \ElggUpgrade();
+
+	// Create the upgrade if one with the same URL doesn't already exist
+	if (!$upgrade->getUpgradeFromPath($path)) {
+		$upgrade->setPath($path);
+		$upgrade->title = 'Comments Access Upgrade';
+		$upgrade->description = 'Some comments on this system have different access settings than their containers.  Run this upgrade to synchronize comment access.';
```
Comment (hypeJunction) [inline engine/lib/upgrades/2015031300-1.11.0_dev-comment-access-sync-50c9764e5845315c.php]: Do you we have an opinion on using North American style double space after a period?

File: engine/tests/ElggCommentTest.php [hunk 6]
```diff
@@ -0,0 +1,58 @@
...
+		$this->comment->access_id = $this->container->access_id;
+		$this->comment->save();
+	}
+
+	public function testCommentAccessSync() {
+		
+		_elgg_disable_caching_for_entity($this->comment->guid);
+		_elgg_disable_caching_for_entity($this->container->guid);
+		
+		$this->assertTrue($this->comment->access_id == $this->container->access_id);
```
Comment (hypeJunction) [inline engine/tests/ElggCommentTest.php]: ->assertEquals()?

**Comment by hypeJunction** [comment]
I am wondering if we should create a new method (maybe ```ElggEntity``` or its own service) that will take ```$type, $subtype``` as arguments and sync access of all contained entities of a given subtype to that of an entity. The reason I am suggesting this is that ```discussion_update_reply_access_ids``` uses the same logic, and I believe plugins are using these batch operations as well.

**Comment by hypeJunction** [comment]
Travis is complaining about lint:

FILE: /home/travis/build/Elgg/Elgg/engine/lib/comments.php
--------------------------------------------------------------------------------
FOUND 1 ERROR(S) AFFECTING 1 LINE(S)
--------------------------------------------------------------------------------
 301 | ERROR | Missing @return tag in function comment

File: engine/classes/ElggEntity.php (hunk 1 above)
Comment (beck24) [inline engine/classes/ElggEntity.php]: I thought the before/after functions were there for just this reason

This doesn't really work without the after hook, as a plugin/something could prevent the update, but then the comments would get changed to a different access_id - making the situation worse.

File: engine/lib/comments.php (hunk 3 above)
Comment (beck24) [inline engine/lib/comments.php]: yes we do, thanks!

File: engine/lib/upgrades/2015031300-1.11.0_dev-comment-access-sync-50c9764e5845315c.php (hunk 5 above)
Comment (beck24) [inline engine/lib/upgrades/2015031300-1.11.0_dev-comment-access-sync-50c9764e5845315c.php]: I didn't realize that was a North American thing.  That's just how I've always done it.  Seems strange to me otherwise.

File: engine/lib/comments.php (hunk 4 above)
Comment (beck24) [inline engine/lib/comments.php]: oh, if that's the case I don't like that convention :(

**Comment by beck24** [comment]
I was thinking the same thing about a generic method to handle other types, wasn't sure about the best way to go about it and I wanted this fixed asap.

File: engine/classes/ElggEntity.php (hunk 1 above)
Comment (beck24) [inline engine/classes/ElggEntity.php]: ```It will be a major pain point for plugin upgrades```
I wouldn't call it a major pain point - append ':before' or ':after' to the registration event.  Minor inconvenience at best :)

Having it's own entry in the logs is a decent point though.

File: engine/lib/upgrades/2015031300-1.11.0_dev-comment-access-sync-50c9764e5845315c.php (hunk 5 above)
Comment (hypeJunction) [inline engine/lib/upgrades/2015031300-1.11.0_dev-comment-access-sync-50c9764e5845315c.php]: Yep, very American of you. The rest of the world just uses a single space, and measurements that are increments of 10.

File: engine/classes/ElggEntity.php (hunk 1 above)
Comment (hypeJunction) [inline engine/classes/ElggEntity.php]: So much for less intrusive deprecation behaviour ;) I don't think any of the older events would need to use :before, so maybe there is a way to make this work without deprecation warning.

File: engine/lib/comments.php [hunk 7]
```diff
@@ -290,6 +292,63 @@ function _elgg_comments_notification_email_subject($hook, $type, $returnvalue, $
...
+		// and to ensure write permissions
+		$ia = elgg_set_ignore_access(true);
+		$options = array(
+			'type' => 'object',
+			'subtype' => 'comment',
+			'container_guid' => $entity->getGUID(),
+			'wheres' => array(
+				"e.access_id != {$entity->access_id}"
+			),
+			'limit' => 0,
```
Comment (juho-jaakkola) [inline engine/lib/comments.php]: I don't know about any convention, but I always use ```false```.

File: engine/lib/upgrades/2015031300-1.11.0_dev-comment-access-sync-50c9764e5845315c.php (hunk 5 above)
Comment (ewinslow) [inline engine/lib/upgrades/2015031300-1.11.0_dev-comment-access-sync-50c9764e5845315c.php]: Latest I've heard is that single space is preferred, even in America. :)

Increments of 10 is silly. 12, 3, 5280. Those are the better numbers. ;)

**Comment by ewinslow** [comment]
I wish this did not have to be an upgrade and instead was a computed property. This is bound to go or of sync some time in someone's repo because of some bad plugin, no?

**Comment by beck24** [comment]
The only way I can see it getting out of sync after this is if someone deliberately unregisters the event handler, or prevents the comment update with an event handler.  Or a database interruption I suppose, but that's a risk on any operation.

After the upgrade is complete we could occasionally run a global check/fix on cron.

File: engine/lib/comments.php (hunk 7 above)
Comment (beck24) [inline engine/lib/comments.php]: I looked at what the discussions batch for this did and it used 0, but I do prefer ```false```

File: engine/lib/upgrades/2015031300-1.11.0_dev-comment-access-sync-50c9764e5845315c.php (hunk 5 above)
Comment (beck24) [inline engine/lib/upgrades/2015031300-1.11.0_dev-comment-access-sync-50c9764e5845315c.php]: Don't lump me in as American, @hypeJunction, I'm militaristically metric!
I'll remove the offending space

File: engine/classes/ElggEntity.php (hunk 1 above)
Comment (beck24) [inline engine/classes/ElggEntity.php]: Technically all this needs to work is the after event.  I could leave the old update event in place, it just seemed logical that if I was adding the after event it should have a matching before event

File: actions/admin/upgrades/upgrade_comments_access.php [hunk 8]
```diff
@@ -0,0 +1,86 @@
...
+
+// Offset is the total amount of errors so far. We skip these
+// comments to prevent them from possibly repeating the same error.
+$offset = get_input('offset', 0);
+$limit = 50;
+
+$access_status = access_get_show_hidden_status();
+access_show_hidden_entities(true);
+
+// don't want any event or plugin hook handlers from plugins to run
```
Comment (mrclay) [inline actions/admin/upgrades/upgrade_comments_access.php]: If we're going to disable all this stuff, wouldn't raw queries be a lot faster?

File: actions/admin/upgrades/upgrade_comments_access.php [hunk 9]
```diff
@@ -0,0 +1,86 @@
...
+$original_events = _elgg_services()->events;
+$original_hooks = _elgg_services()->hooks;
+_elgg_services()->events = new Elgg\EventsService();
```
Comment (mrclay) [inline actions/admin/upgrades/upgrade_comments_access.php]: Altering the ServiceProvider is actually not reliable because services increasingly hold references to the originals in private properties. /cc @ewinslow

Comment (mrclay) [inline actions/admin/upgrades/upgrade_comments_access.php]: Removing all the handlers and restoring them after would be the way to go. I don't know if we make that possible at the moment.

Comment (mrclay) [inline actions/admin/upgrades/upgrade_comments_access.php]: Or introducing a "disabled" mode on the hooks/events that hides the handlers.

File: engine/classes/ElggEntity.php (hunk 1 above)
Comment (mrclay) [inline engine/classes/ElggEntity.php]: I vaguely remember a good reason I didn't migrate entity "update" to before/after events, and I don't recall what it was!

Comment (mrclay) [inline engine/classes/ElggEntity.php]: @beck24 I think leaving "update" as is and adding "update:after" is an OK compromise. We'd need to mention it in the RST docs

File: engine/lib/comments.php [hunk 10]
```diff
@@ -290,6 +292,63 @@ function _elgg_comments_notification_email_subject($hook, $type, $returnvalue, $
...
+ * 
+ * @param string     $event  'update:after'
+ * @param string     $type   'all'
+ * @param ElggEntity $entity The updated entity
+ * @return bool
+ * 
+ * @access private
+ */
+function _elgg_comments_access_sync($event, $type, $entity) {
+	if ($entity instanceof \ElggEntity) {
```
Comment (mrclay) [inline engine/lib/comments.php]: if not an entity, return true (early).

File: engine/lib/comments.php [hunk 11]
```diff
@@ -290,6 +292,63 @@ function _elgg_comments_notification_email_subject($hook, $type, $returnvalue, $
...
+			'type' => 'object',
+			'subtype' => 'comment',
+			'container_guid' => $entity->getGUID(),
+			'wheres' => array(
+				"e.access_id != {$entity->access_id}"
+			),
+			'limit' => 0,
+		);
+
+		$batch = new \ElggBatch('elgg_get_entities', $options, null, 25, false);
```
Comment (mrclay) [inline engine/lib/comments.php]: Don't we allow `'batch' => true` yet?

Comment (beck24) [inline engine/lib/comments.php]: I saw you refactored my PR for that which looked much better, but I didn't see it get merged in.  If it did then we can certainly use that.

File: actions/admin/upgrades/upgrade_comments_access.php (hunk 9 above)
Comment (beck24) [inline actions/admin/upgrades/upgrade_comments_access.php]: I was just reusing the patterns from the 1.9 comments upgrade here, but direct queries would be faster.  I'm kind of torn about whether we should be letting the events fire on the upgrade.  I think the only reason to not allow them is performance, but that's not likely to be too much of an issue.  Potentially plugins preventing the update, but if they're doing that then this is pointless anyway as the event handler to synchronize them will fail consistently as well.  I guess we can't be responsible for what plugins might do with such an open system.

File: engine/classes/ElggEntity.php (hunk 1 above)
Comment (beck24) [inline engine/classes/ElggEntity.php]: ok, I'll remove the deprecation and leave 'update' as is with the added 'update:after'

File: engine/lib/comments.php (hunk 11 above)
Comment (beck24) [inline engine/lib/comments.php]: https://github.com/Elgg/Elgg/pull/7723

Looks like it just needs a one line doc change and ```extend Countable and Iterator for Elgg\BatchInterface```

**Comment by mrclay** [comment]
The access_id also needs to inherit into likes on the comments, so we probably have to call events, right?

**Comment by beck24** [comment]
Yes, I have the event calls in the most recent iteration here

File: actions/admin/upgrades/upgrade_comments_access.php [hunk 12]
```diff
@@ -0,0 +1,74 @@
...
+			"e.access_id != e2.access_id"
+		),
+		'offset' => $offset,
+		'limit' => $limit
+	);
+			
+	$comments = elgg_get_entities($options);
+	
+	foreach ($comments as $comment) {
+		$container = $comment->getContainerEntity();
```
Comment (mrclay) [inline actions/admin/upgrades/upgrade_comments_access.php]: Maybe check the container is actually loaded?

File: actions/admin/upgrades/upgrade_comments_access.php [hunk 13]
```diff
@@ -0,0 +1,74 @@
...
+		'type' => 'object',
+		'subtype' => 'comment',
+		'joins' => array(
+			"JOIN {$dbprefix}entities e2 ON e.container_guid = e2.guid"
+		),
+		'wheres' => array(
+			"e.access_id != e2.access_id"
+		),
+		'offset' => $offset,
+		'limit' => $limit
```
Comment (mrclay) [inline actions/admin/upgrades/upgrade_comments_access.php]: `'preload_containers' => true,`

File: actions/admin/upgrades/upgrade_comments_access.php [hunk 14]
```diff
@@ -0,0 +1,74 @@
...
+	
+	foreach ($comments as $comment) {
+		$container = $comment->getContainerEntity();
+		
+		$comment->access_id = $container->access_id;
+		
+		if ($comment->save()) {
+			$success_count++;
+		}
+		else {
```
Comment (mrclay) [inline actions/admin/upgrades/upgrade_comments_access.php]: Should be on previous line

File: actions/admin/upgrades/upgrade_comments_access.php (hunk 12 above)
Comment (beck24) [inline actions/admin/upgrades/upgrade_comments_access.php]: ok, will do.  This is run with hidden status and access overridden, so there shouldn't be any case where the container can't be loaded unless there's a data problem where the container is missing or broken.  In that case what do you think we should do with it?

Comment (beck24) [inline actions/admin/upgrades/upgrade_comments_access.php]: Just decided to skip it and record it as an error.  There's no good way to predict what should happen.  Devs will have to sort out their own data corruption.

**Comment by twentyfiveautumn** [comment]
If someone makes a comment based on the entity is access_friends and then the entity gets changed to access_public how will that work? Will the comment still be access_friends?

**Comment by beck24** [comment]
That's how it currently works, but with this the comment will change to be access_public - it will be kept in sync with the entity.

**Comment by twentyfiveautumn** [comment]
So in this scenario if you commented on my post and then I change the access if effect I'm changing the access permission on a comment I don't own? I see the issue as it's not okay for a comment to be less restrictive than the entity but shouldn't it be okay for the comment to be more restrictive than the entity? I'm just looking to honor the privacy settings of the comment owner. Thanks...

**Comment by hypeJunction** [comment]
IMHO, comment owner should not even be able to control the privacy of a
comment. Comment threads would make no sense if you omitted half the
comments due to their privacy settings.

**Comment by twentyfiveautumn** [comment]
@hypeJunction 
the comment is an entity so the entity owner should not have control over the privacy setting?
IMHO it's to make the comment more restrictive but it's not okay to make it less restrictive. 
I'm just trying to look at it from the user point of view

**Comment by hypeJunction** [comment]
The point here is not to give a user a perspective. No other social network
allows you to customize privacy of a comment. Why would you even have an
option to make a private comment - send a message instead.
I mean the UI should not even give an option to change access if of a
comment. Imagine github allowing the change of privacy on this comment and
I would set it to elgg repo owners, you would never see this comment. If
Matt referenced my comment you would be completely lost.
I would even suggest adding magic ACLs for anything that relies on
container access id (-2) and owner access id (-3) and build those in to the
access query.

**Comment by twentyfiveautumn** [comment]
@hypeJunction 
I do understand your point and from an Admin perspective this all works. But as a user I might comment on your post based on the fact that it's marked access_friends where I would not have commented if it was marked access_public. And if you add magic ACLs I respect your privacy and you have the absolute right to do so.

**Comment by hypeJunction** [comment]
Ah, now I get your point. Sounds like a valid concern. Not sure how to
address that though.

**Comment by twentyfiveautumn** [comment]
Thanks @hypeJunction 
95% of what you guys do here is over my head but I bet Matt can fix it...

**Comment by beck24** [comment]
If you comment on something with the expectation of privacy based on the entity being commented on, you are trusting the person who owns the content with your comment.  If they change the access the comment changes with it, that's the logical behavior.  It's no different than them copy/pasting your comment or posting a screenshot of it.  The issue is a trust issue between the commenter and the content owner, not a technical issue.
It's been discussed at length prior to this - having comments with different access creates a ton of problems.  If an individual site wants to keep the old broken behavior they can unregister the sync event.

**Comment by twentyfiveautumn** [comment]
@beck24 
Hi Matt, It's really not my intention to be a pain in the ass but it is different. If the entity owner copies/pastes my comment or does a screenshot then you are right it's a trust issue between me and them. The difference here is we (elgg) are giving one user the ability to override another users privacy settings. 
It's no big deal until someone lose their job, gets divorced or something else because we allowed the change. And even if there is no harm but the user realizes we changed their privacy setting then the trust is gone. Food for thought.

**Comment by beck24** [comment]
Can you give me *any* real life example where a comment thread with varied access exists and/or makes sense?

**Comment by twentyfiveautumn** [comment]
For me it's not about that, it's about honoring the users privacy settings. I don't want some website changing my privacy settings, do you?

**Comment by beck24** [comment]
but it's not, you're not explicitly setting access on your comments.  Comments work on inherited access.

**Comment by twentyfiveautumn** [comment]
But it would allow another user to take a comment we intended for a specific audience and make it public? Just a privacy concern, that's all.

**Comment by beck24** [comment]
Yes it would, same as can be done in any other comment software - including facebook and google plus, or any forums with replies.
As I said earlier, if you want the old broken implementation you could unregister the sync event.  But they you have to live with all of the problems that it causes.

**Comment by twentyfiveautumn** [comment]
Because the others all do it is not really strong augment but I do appreciate your position. Thanks for taking the time to talk with me about it.
Ray

**Comment by ewinslow** [comment]
Fwiw, Google plus does not allow changing the acl of a post once it is posted because of this issue that Ray is mentioning.

Obviously there is always the possibility of copy pasting or posting a screenshot, but in that case the user is clearly circumventing the system and can't blame it on the system's surprising privacy properties.

I have been frustrated by this privacy feature in the past

**Comment by ewinslow** [comment]
One thing that is helpful that I've seen g+ do is warn you if you are about to reshare a post with a wider audience.

**Comment by beck24** [comment]
What I meant about referencing other software is that it shouldn't be considered "surprising" behavior.  Having a thread of comments where some people can only see some comments and other can people can see other comments (and these permissions are not explicitly set) is what we have now, and that I think is the surprising behavior.

**Comment by twentyfiveautumn** [comment]
I think what we should really be asking ourselves is "What is the right thing to do?"

**Comment by beck24** [comment]
For core the right thing to do is what will best suit the majority of users.  I think this is it.  Anything different is certainly going to be a specific decision on a per-site basis.  It's trivial to change in a plugin.

**Comment by twentyfiveautumn** [comment]
For me personally the privacy of the user outweighs all other considerations but we can agree to disagree . :)

**Comment by beck24** [comment]
That's fine, to revert this in a plugin is literally a one-liner
```elgg_unregister_event_handler('update:after', 'all', '_elgg_comments_access_sync');```

**Comment by ewinslow** [comment]
Can we get some kind of warning in the ui when the user attempts to change access control on an item with comments?

**Comment by beck24** [comment]
The input/access view could be extended, and the entity checked for the presence of comments and a warning displayed inline near the access control.
Or some data attributes could be added to the access input indicating an original value.  Then js can check if the access is changing and do a confirmation.  Assuming of course that the entity itself is passed to the input/access view.

**Comment by twentyfiveautumn** [comment]
How about a setting on the Admin side the gives the website Admin the option to turn it off? I think that's a good compromise.

**Comment by hypeJunction** [comment]
I don't think the core should encourage this by providing a setting. Site owners will be just exposing themselves to unpredictable behaviour including WSOD, as we have seen in the Elgg community. Developers that know what they are doing can unregister the hook, and spend their time resolving resulting bugs.

**Comment by twentyfiveautumn** [comment]
Point well taken @hypeJunction I see the real question as is our need to fix WSOD more important than user privacy?

**Comment by hypeJunction** [comment]
Arguments for privacy in this case are not convincing. IMHO, you should inform your users about commenting policy in your privacy policy, and let them decided if they want to comment. At the end of the day, those concerned with privacy shouldn't engage with content posted by others. If they want to have a discussion on an issue they can start one with the privacy setting of their own.

**Comment by jeabakker** [comment]
My 2 cents. I don't like the idea of syncing the access of the comments with the entity. This has never been the case in Elgg, why start now? Just because we couldn't catch the fault case, we can (and should)

> Can you give me any real life example where a comment thread with varied access exists and/or makes sense?

User A writes an offensive blog, user B reports this to the admins. The admins check and agree with user B. The admins change the blog post to private and comment on it to inform user A that they should change the content of the blog. User A complies and rewrites the blog and set the access to > private.
The comment of the admin about the change should not be visible to the rest of the community, right?!

**Comment by hypeJunction** [comment]
Why not have an admin delete the post and have the poster write a new one?

**Comment by jeabakker** [comment]
> Why not have an admin delete the post and have the poster write a new one?

what if that is not allowed by company policy?

**Comment by twentyfiveautumn** [comment]
medical records, political campaign, union activity, domestic abuse issues, just off the top of my head are the types of thing that could be negatively impacted buy this. It's just not a good way to go. There must be other options.

**Comment by hypeJunction** [comment]
Disable?

**Comment by hypeJunction** [comment]
I am all up for other solutions. So far I only heard this doesn't work for
me - what will then? Syncing seems like the simplest solution. If anyone
can submit an alternative PR I am sure we will gladly consider it. And this
is only a temporary solution until the collections API is in place.

**Comment by hypeJunction** [comment]
As was told earlier, if you are dealing with sensitive information,
unregister the hook and implement your own logic. We are talking about
comments here not medical records.

**Comment by jeabakker** [comment]
> So far I only heard this doesn't work for me - what will then?

i just made a fix for a client of our where i just catch the fact that the container (where the comment is on) is not accessable and make a different text.

Will submit pr soon

**Comment by mrclay** [comment]
The admin could communicate with the user not through comments. Point being this is an extremely narrowly constructed hypothetical situation so counter arguments can weasel out of it.

We should probably discuss on the community what the most common cases are and the behavior least surprising to most users. The answer may be syncing in some cases and not others.

**Comment by twentyfiveautumn** [comment]
I never did get the question answered "do you want some website changing your privacy settings?". But as log as I have an unregister hook I'll deal with it.

**Comment by mrclay** [comment]
As I mentioned in an older ticket, from the perspective of the commentor's privacy, not altering the comment's access level is a feature. I think the desires of the content author to change access level have to come second.

**Comment by ewinslow** [comment]
@mrclay what about a UI warning?

Also consider the case of email -- you can forward a whole conversation to new people, or add people to the conversation and have them see the whole history.

My opinion is that a UI warning about the social hazards of changing access levels would be a good compromise.

**Comment by beck24** [comment]
@jeabakker ```This has never been the case in Elgg, why start now?```

This currently happens for replies to group discussions for the same reasons.

**Comment by ewinslow** [comment]
Historical precedent doesn't hold much weight for me in general. Lots of things can be done wrong for a long time...

**Comment by hypeJunction** [comment]
Can I suggest that elgg owners take a vote to either pull this in or close?
It's too much blah blah.

**Comment by twentyfiveautumn** [comment]
I think a better way to go is if the logged in user can not see the entity then don't show the comments either. And still no one has answered the question "do you want some website changing your privacy settings?".

I'm a privacy advocate, I just am.

**Comment by beck24** [comment]
```I think a better way to go is if the logged in user can not see the entity then don't show the comments either.```
That's exactly what this PR will do.

```do you want some website changing your privacy settings```
You are exaggerating the issue, this isn't changing someones privacy settings.  If the person doesn't choose a privacy setting when they're creating the comment, it's not changing a setting for them.

**Comment by twentyfiveautumn** [comment]
@beck24 You are correct on  "that's exactly what this PR will do" as long as the entity owner is making the access_id more restrictive but not if there making it less restrictive.
I'm new so maybe I'm missing something?

Was that a yes or no to having a website change your privacy settings?

**Comment by ewinslow** [comment]
@twentyfiveautumn That was a no.

**Comment by ewinslow** [comment]
Agreed that we need a vote.

**Comment by twentyfiveautumn** [comment]
+1 on a vote

**Comment by beck24** [comment]
Agreed - vote initiated at the top of the thread

**Comment by beck24** [comment]
@mrclay - just saw your vote.  I'm fine with both of those conditions - would you want the UI message added to this PR?
Next is the question of how we define expanding access.  That could be tricky to decide when you consider custom acls, probably requiring an ajax callback to do an array diff of acl membership.  It could be useful to have a notice when restricting the access as well.  Maybe something generic-but-informative on any change?

**Comment by mrclay** [comment]
Same PR seems fine; up to you. A generic message that appears on any access_id select change seems sufficient.

**Comment by twentyfiveautumn** [comment]
This feels like a backdoor but letting the user know it's there is certainly a good step in the right direction. Thank you for that. My intention here has always been to look out for the interest of all users on all Elgg websites. Thanks again
Ray

**Comment by twentyfiveautumn** [comment]
When you strip away the debate and opinions here the actual issue is simple:
The code allows a user to change the access_id of an entity they do not own.
Some see no harm in that, others do.
That's the entire issue.
I do apologize to anyone I've offended along the way.
Ray

**Comment by mrclay** [comment]
@twentyfiveautumn I may *own* that entity, but it's an Elgg system implementation detail that ElggComments have independent access control and ownership. If I comment on someone else's WordPress blog, they retain some rights to moderate my comment in various ways and I see that as reasonable.

I think contextual help to explain features/site policies to users would be helpful but ultimately the demand from developers hasn't been that great for it.

**Comment by mrclay** [comment]
Sorry everyone, we can move our discussion to the community.

**Comment by beck24** [comment]
I've created a new ticket for the UI feedback as this is ready to merge and I think we're all done with this thread!
