### PR TITLE
fix(annotations): save/update annotations return false on null values

### LINKED ISSUE #14014: return false for ElggAnnotation->save() if name/value is empty
- [ ] add test

### PR DESCRIPTION
**Pull request by jdalsem**
fixes #14014

### CODE REVIEW

File: engine/tests/phpunit/integration/Elgg/Database/AnnotationsTableIntegrationTest.php [hunk 1]
```diff
@@ -0,0 +1,105 @@
...
+
+class AnnotationsTableIntegrationTest extends IntegrationTestCase {
+
+	/**
+	 * @var AnnotationsTable
+	 */
+	protected $service;
+
+	/**
+	 * @var ElggUser
```
Comment (jeabakker) [inline engine/tests/phpunit/integration/Elgg/Database/AnnotationsTableIntegrationTest.php:15]: `\ElggUser`

**Review by jeabakker — APPROVED** [review]

File: engine/classes/Elgg/Database/AnnotationsTable.php [hunk 2]
```diff
@@ -112,7 +116,7 @@ public function create(\ElggAnnotation $annotation, \ElggEntity $entity) {
 		//	return false;
 		//}
 
-		if (!$this->events->trigger('annotate', $entity->getType(), $entity)) {
+		if (!$this->events->triggerDeprecated('annotate', $entity->getType(), $entity, "The 'annotate', '{$entity->getType()}' event is deprecated. Use the 'create', 'annotation' event instead.", '4.3')) {
```
Comment (jeabakker) [inline engine/classes/Elgg/Database/AnnotationsTable.php:119]: .... use the event **sequence** instead ....

File: engine/tests/phpunit/integration/Elgg/Database/AnnotationsTableIntegrationTest.php [hunk 3]
```diff
@@ -0,0 +1,105 @@
...
+
+	public function testCreateAnnotation() {
+		$entity = $this->createObject();
+
+		$annotation = new \ElggAnnotation();
+		$annotation->owner_guid = $this->owner->guid;
+		$annotation->name = 'foo';
+		$annotation->value = 'bar';
+		
+		$this->assertIsInt($this->service->create($annotation, $entity));
```
Comment (jeabakker) [inline engine/tests/phpunit/integration/Elgg/Database/AnnotationsTableIntegrationTest.php:36]: You didn't check that the correct data was saved to the database.
After the save, load it from the database and verify the data is saved correctly

**Review by jeabakker — CHANGES_REQUESTED** [review]

**Review by jeabakker — APPROVED** [review]
