### PR TITLE
chore(uservalidationbyemail): Fixes check all on unvalidated users page

### LINKED ISSUE #8966: Uservalidationbyemail javascript is broken
The "All" checkbox in site.com/admin/users/unvalidated does not work.

### PR DESCRIPTION
**Pull request by mrclay**
Fixes #8966

### CODE REVIEW

File: mod/uservalidationbyemail/views/default/uservalidationbyemail/js.php [hunk 1]
```diff
@@ -1,27 +1,28 @@
+//<script>
 
 elgg.provide('elgg.uservalidationbyemail');
 
 elgg.uservalidationbyemail.init = function() {
 	$('#uservalidationbyemail-checkall').click(function() {
-		var checked = $(this).attr('checked') == 'checked';
```
Comment (mrclay) [inline mod/uservalidationbyemail/views/default/uservalidationbyemail/js.php]: These 3 lines were the fix, other lines are clean up.
