### PR TITLE
fix(navigation): added helper class for parents of selected menu items

### LINKED ISSUE #12129: current selected menu item is missing a way to target actual item
`elgg-state-selected` is set on every menu item that is part of the selected tree, but the current/active menu item is not targetable this way. I need the last item in the tree selected / highlighted... not the whole tree.

### PR DESCRIPTION
**Pull request by jeabakker**
fixes #12129

### CODE REVIEW

File: engine/lib/navigation.php [hunk 1]
```diff
@@ -693,6 +693,7 @@ function _elgg_setup_vertical_menu(\Elgg\Hook $hook) {
 		$parent = $selected_item->getParent();
 		while ($parent instanceof \ElggMenuItem) {
 			$parent->setSelected();
+			$parent->addItemClass('elgg-menu-item-has-selected-child');
```
Comment (hypeJunction) [inline engine/lib/navigation.php]: Can is it just be `has-selected-child`?
Imagine targeting this with `.elgg-menu-item.elgg-menu-item-has-selected-child`

Comment (jeabakker) [reply engine/lib/navigation.php]: will change it to `elgg-has-selected-child` OK?
