### PR TITLE
fix(js): correctly define amd dependencies for input/userpicker

### LINKED ISSUE #5296: input/userpicker can't be used in a lightbox
Lightboxes fail to load if the content includes a userpicker

### PR DESCRIPTION
**Pull request by jdalsem**
fixes #5296 

additionally defines jquery.ui and jquery.ui.autocomplete.html for use in AMD.

There is no conflict if you mix loading js with elgg_load_js and a requirement/dependency in requirejs.

Any comments on this @ewinslow?

### CODE REVIEW

File: engine/lib/elgglib.php [hunk 1]
```diff
@@ -1899,6 +1899,11 @@ function _elgg_init() {
 	elgg_register_js('elgg.autocomplete', 'js/lib/ui.autocomplete.js');
 	elgg_register_js('jquery.ui.autocomplete.html', 'vendors/jquery/jquery.ui.autocomplete.html.js');
```
Comment (jdalsem) [inline engine/lib/elgglib.php]: left this intact for BC purposes, but could be removed in 2.0

Comment (ewinslow) [inline engine/lib/elgglib.php]: Leave a `TODO(jdalsem): Remove in 2.0?`

File: engine/lib/views.php [hunk 2]
```diff
@@ -1624,6 +1624,10 @@ function elgg_views_boot() {
 		'deps' => array('jquery'),
 		'exports' => 'jQuery.fn.ajaxForm',
 	));
+	elgg_define_js('jquery.ui', array(
+		'src' => '/vendors/jquery/jquery-ui-1.10.4.min.js',
+		'deps' => array('jquery'),
```
Comment (ewinslow) [inline engine/lib/views.php]: Is there an "exports" value you can add here? Or does jquery-ui already declare itself as an AMD module?

File: views/default/js/elgg/UserPicker.js [hunk 3]
```diff
@@ -1,7 +1,6 @@
 /** @module elgg/UserPicker */
 
-define(['jquery', 'elgg'], function ($, elgg) {
-
+define(['jquery', 'elgg', 'jquery.ui.autocomplete.html'], function ($, elgg) {
```
Comment (ewinslow) [inline views/default/js/elgg/UserPicker.js]: Very cool.

**Comment by ewinslow** [comment]
I like it. Assuming you've tested and address the comments, feel free to pull this in.

Should we be worried about people implicitly dependending on elgg_load_js having been called? I would think no, but if it breaks people they will scream anyway...
