### PR TITLE
fix(simplecache): removes warning about using mkdir() when cache directory exists

### LINKED ISSUE #9219: Flood of "mkdir(): File exists" warnings on SimpleCache reset
Warnings refer to invalidate() function: https://github.com/Elgg/Elgg/blob/2.0/engine/classes/Elgg/Cache/SimpleCache.php#L177.

I see a `mkdir()` in this line followed by a `_elgg_rmdir()` in the next line. Could it be that it should be the other way round, i.e. first removal and then re-creation?

### PR DESCRIPTION
**Pull request by juho-jaakkola**
Fixes #9219

### CODE REVIEW

File: engine/classes/Elgg/Cache/SimpleCache.php [hunk 1]
```diff
@@ -174,13 +174,12 @@ private function getPath() {
 	 * @return bool
 	 */
 	function invalidate() {
-		mkdir($this->getPath());
 		_elgg_rmdir($this->getPath(), true);
```
Comment (juho-jaakkola) [inline engine/classes/Elgg/Cache/SimpleCache.php]: Passing `true`as the second parameter means that the directory gets just emptied but not removed. Therefore `mkdir()` is not needed at all.
