### PR TITLE
fix(files): now uses filename on filestore to detect mime

### LINKED ISSUE #8846: MIME being checked on missing file (maybe before file save)
Test path with `file_exists()` before calling `finfo_file()` or `mime_content_type()`

### PR DESCRIPTION
**Pull request by hypeJunction**
For ElggFile instances ElggFile::detectMimeType was using filename metadata,
which was not a readable file. Now normalizes filename to a filestore path,
and ensures that the file is readable before calling finfo_\* and mime_*

Fixes #8846

### CODE REVIEW

File: engine/classes/ElggFile.php [hunk 1]
```diff
@@ -154,9 +154,10 @@ public function detectMimeType($file = null, $default = null) {
 			$mime = mime_content_type($file);
 		}
 
+		$original_filename = isset($this) ? $this->originalfilename : basename($file);
```
Comment (mrclay) [inline engine/classes/ElggFile.php]: Can you add a `@note` in the phpdoc that we're calling this both dynamically and statically?

**Comment by mrclay** [comment]
Besides that, looks OK to me.

**Comment by juho-jaakkola** [comment]
LGTM
