### PR TITLE
fix(php): Suppress mysql_connect() deprecation warnings for core

### LINKED ISSUE #9245: Suppress ext/mysql deprecation notices in 1.12
These aren't helpful and fill logs with noise.

### PR DESCRIPTION
**Pull request by mrclay**
Elgg 2.0 no longer uses ext/mysql, so these warnings are just a nuisance for 1.x site owners and plugin devs.

Fixes #9245

(I've verified this catches the warning, but on my system returning `true` still allows it to be sent to my log. I suspect this is an xdebug/environment problem.)

### CODE REVIEW

File: engine/lib/elgglib.php [hunk 1]
```diff
@@ -881,6 +881,14 @@ function _elgg_php_exception_handler($exception) {
  * @todo Replace error_log calls with elgg_log calls.
  */
 function _elgg_php_error_handler($errno, $errmsg, $filename, $linenum, $vars) {
+
+	if (0 === strpos($errmsg, "mysql_connect(): The mysql extension is deprecated")) {
+		// only suppress core's usage
```
Comment (juho-jaakkola) [inline engine/lib/elgglib.php]: Add the description from the PR also here to clarify why they are being suppressed.

**Comment by juho-jaakkola** [comment]
LGTM
