### PR TITLE
fix(annotations): simplifies ege* for annotation calculations

### LINKED ISSUE #7398: elgg_get_entities_from_annotation_calculation() doesn't allow custom callbacks
The function just greedily overwrites ```$options['callback']```. Not sure it's even needed there, let ```ege``` handle it?

### PR DESCRIPTION
**Pull request by hypeJunction**
Annotations::getEntitiesFromCalculation() now allows custom or no callback. Passing count => true to elgg_get_entities_from_annotation_calculation() now uses elgg_get_entities_from_annotations() (this removes the magic and flags used previously). Adds more egefac() tests and cleans up some of the lint.

Fixes #7398, #4393

### CODE REVIEW

**Comment by hypeJunction** [comment]
@ewinslow This was waiting for your review

File: engine/classes/Elgg/Database/Annotations.php [hunk 1]
```diff
@@ -384,6 +379,10 @@ function getEntities(array $options = array()) {
 	/**
 	 * Get entities ordered by a mathematical calculation on annotation values
 	 *
+	 * @tip Note that this function uses { @link elgg_get_annotations() } to return a list of entities ordered by a mathematical
+     * calculation on annotation values, and { @link elgg_get_entities_from_annotations() } to return a count of entities
```
Comment (mrclay) [inline engine/classes/Elgg/Database/Annotations.php]: spaces?

**Comment by hypeJunction** [comment]
@mrclay fixed spacing issues

**Comment by mrclay** [comment]
LGTM. @ewinslow if you're still interested in taking a look please do. Otherwise ready to merge.

**Comment by ewinslow** [comment]
I trust y'all here
