### PR TITLE
fix(ckeditor): ensure basepath is set before CKeditor is loaded

### LINKED ISSUE #10304: CKeditor not always loaded (on Elgg community site at least)
Sometimes it works, sometimes it doesn't and then I only see a plaintext input field. Refreshing the page helps but this is not satisfying...

### PR DESCRIPTION
**Pull request by mrclay**
This converts `set-basepath.js` to a real module and makes sure it's run before `ckeditor.js` is loaded. Previously we wrongly assumed ckeditor would always be loaded after elgg.js ran all `require()` scripts.

Fixes #10304

(I'm not sure this is fully BC, but see no other way to fix it.)

### CODE REVIEW

File: mod/ckeditor/views/default/elgg/ckeditor/set-basepath.js [hunk 1]
```diff
@@ -1,7 +1,8 @@
 /**
  * This view extends elgg.js and sets ckeditor basepath before jquery.ckeditor is loaded
  */
-require(['elgg'], function(elgg) {
+define('elgg/ckeditor/set-basepath', function (require) {
+	var elgg = require('elgg');
```
Comment (jdalsem) [inline mod/ckeditor/views/default/elgg/ckeditor/set-basepath.js]: if you do not need require, i like this syntax more...
```js
define(['elgg'], function() {
```

elgg will translate that to
```js
define('elgg/ckeditor/set-basepath', ['elgg'], function() {
```

nonetheless... this LGTM

**Review by hypeJunction — APPROVED** [review]

File: mod/ckeditor/views/default/elgg/ckeditor/set-basepath.js (hunk 1 above)
Comment (mrclay) [inline mod/ckeditor/views/default/elgg/ckeditor/set-basepath.js]: If you inline in elgg.js you have to include the explicit name.

Comment (jdalsem) [inline mod/ckeditor/views/default/elgg/ckeditor/set-basepath.js]: check
