### PR TITLE
fix(js): prevent clicks until related js is loaded

### LINKED ISSUE #10489: Users can interact with elements before event listeners are registered
Our page rendering performance is great, but it means interactive elements are presented before event listeners have been registered.

The "progressive enhancement" solution of defaulting to usable links is still problematic. Links to partial views (not complete, or half-baked pages) should never be used. If the current page allows user input, a button that unexpectedly falls back to a link could be disastrous UX.

Strawman: 
1. At top of body, a script would register a click handler on document. If the target element had the attribute `data-elgg-click="name"`, then the event data would be captured under the key "name" and `return false`.
2. A clickable element could include this data attribute to capture early clicks.
3. For that component module, the real listener would be registered, and the data attribute removed.
4. The module could then do as it wished with the captured click data, maybe choosing to re-trigger it.

### PR DESCRIPTION
**Pull request by jdalsem**
fixes #10489

### CODE REVIEW

File: views/default/page/elements/foot.php [hunk 1]
```diff
@@ -1,6 +1,9 @@
 <?php
 
-$elgg_init = elgg_view('initialize_elgg.js');
+// load special js to prevent certain clicks
+$elgg_init = elgg_view('elgg/prevent_clicks.js');
```
Comment (jdalsem) [inline views/default/page/elements/foot.php]: or should i do this with elgg_extend_view('initialize_elgg', 'prevent_clicks', 1); ??

File: views/default/elgg/prevent_clicks.js [hunk 2]
```diff
@@ -0,0 +1,15 @@
+var lightbox_links = document.getElementsByClassName('elgg-lightbox');
```
Comment (jeabakker) [inline views/default/elgg/prevent_clicks.js]: Why does this file exists? What is it's purpose in life?

**Review by jeabakker — CHANGES_REQUESTED** [review]

**Review by jeabakker — APPROVED** [review]
