### PR TITLE
Log messages no longer wrongly discarded

### LINKED ISSUE #9244: Logging fails in non-page requests
Really two different bugs:

1. When log to screen is off, warnings during cache requests end up with `$display == true` in Elgg\Logger::process. I.e. it echoes them, but thankfully it seems that output buffer is discarded so it doesn't break anything.
2. When log to screen in on, messages are dumped into the ElggLogCache for screen output, but that output never occurs. The messages never escape the cache.

### PR DESCRIPTION
**Pull request by mrclay**
**fix(logging): Log messages no longer discarded**

Logged messages are no longer thrown away during action and cache requests.
Also the log-to-screen feature of the developers plugin no longer throws away messages after the page display has occurred.

In both cases, these errors likely end up in the system error log.

Fixes #9244

**chore(views): removes core use of elgg_get_view_location()**

With #9244 fixed, these deprecation warning are no longer thrown away, so we instead use the private API version to avoid them.

### CODE REVIEW

File: engine/classes/Elgg/Logger.php [hunk 1]
```diff
@@ -202,6 +202,16 @@ protected function process($data, $display, $level) {
 			$display = false;
 		}
 
+		// don't display in simplecache requests
+		$this_url = current_page_url();
+		$site_url = elgg_get_site_url();
+		if (0 === strpos($this_url, $site_url)) {
```
Comment (juho-jaakkola) [inline engine/classes/Elgg/Logger.php]: Why is this needed?

Comment (mrclay) [inline engine/classes/Elgg/Logger.php]: I guess that'll always be true. Will update.

**Comment by juho-jaakkola** [comment]
LGTM

**Comment by hypeJunction** [comment]
> Also the log-to-screen feature of the developers plugin no longer throws away messages after the page display has occurred.

What happens to them?

**Comment by mrclay** [comment]
They continue to get logged either to error_log or screen (until shutdown)
