### PR TITLE
Various javascript changes

### LINKED ISSUE #12755: Elgg 3: ajax response with http exception
for example loading a ajax view which is protected by a gatekeeper and between requests your session expired

### LINKED ISSUE #12909: error responses should return HTTP error code
i think it was for BC reasons this was never changed, but i makes not much sense to have 200 status codes on 'page not found' responses (for example). Changing this is breaking so this needs to go in Elgg 4

Ajax calls will benefit a lot by this as they can rely on chaining with `.success` and `.error`

### LINKED ISSUE #13175: Get rid of non AMD ajax functions
like elgg.action

### PR DESCRIPTION
**Pull request by jdalsem**
You now can only use the elgg/Ajax async module.

fixes #13175

fixes #12909

fixes #12755

- [x] remove weakmap and formdata polyfill
- [x] try to split jquery-ui
- [x] investigate issues on theme_sandbox/navigation
- [x] check upgrader.js
- [x] investigate elgg/Plugin use
- [x] what to do with elgg/init and elgg/ready
- [x] combine require and require-config
- [x] elgg/popup should not be required every page load
- [x] revisit javascript docs

### CODE REVIEW

File: views/default/core/js/security.js [hunk 1]
```diff
@@ -72,31 +72,32 @@ elgg.security.refreshToken = function () {
...
+						clearInterval(elgg.security.tokenRefreshTimer);
+						if (data.user_guid) {
+							elgg.register_error(elgg.echo('session_changed_user'));
+						} else {
+							elgg.register_error(elgg.echo('session_expired'));
+						}
 					}
 				}
+			},
+			error: function () {
```
Comment (jeabakker) [inline views/default/core/js/security.js:98]: why not use the option to suppress errors

**Review by jeabakker — CHANGES_REQUESTED** [review]

File: engine/classes/Elgg/Upgrades/DeleteDiagnosticsPlugin.php [hunk 2]
```diff
@@ -28,6 +28,7 @@ public function needsIncrementOffset() {
 	 * {@inheritDoc}
 	 */
 	public function shouldBeSkipped() {
+		return false;
```
Comment (jeabakker) [inline engine/classes/Elgg/Upgrades/DeleteDiagnosticsPlugin.php:31]: oops

**Review by jeabakker — CHANGES_REQUESTED** [review]

File: engine/classes/Elgg/Upgrades/DeleteDiagnosticsPlugin.php (hunk 2 above)
Comment (jdalsem) [reply engine/classes/Elgg/Upgrades/DeleteDiagnosticsPlugin.php:31]: whoops indeed

**Review by jeabakker — APPROVED** [review]
