### PR TITLE
fix(actions): send error HTTP header from action forward hook

### LINKED ISSUE #9027: lightbox and forward
Not sure if there is an easy solution, but whenever a page handler uses `forward()`, lightbox receives and displays a json object. Too bad we use `elgg_is_xhr()` to assume `Accept: application/json`

### PR DESCRIPTION
**Pull request by hypeJunction**
ajax_forward_hook() now sends error HTTP header, if forward reason is an
HTTP error code. This makes sure that response object returned by non-action
URLs is not output as raw string to the user (e.g. when requested by lightbox)

Fixes #9027

### CODE REVIEW

File: engine/classes/Elgg/ActionsService.php [hunk 1]
```diff
@@ -322,7 +322,24 @@ public function ajaxForwardHook($hook, $reason, $return, $params) {
...
+				'401' => 'Unauthorized',
+				'403' => 'Forbidden',
+				'404' => 'Not Found',
+				'407' => 'Proxy Authentication Required',
+				'500' => 'Internal Server Error',
+				'503' => 'Service Unavailable',
+			);
+
+			if (isset($httpCodes[$reason])) {
+				header("HTTP/1.1 $reason {$httpCodes[$reason]}", true);
```
Comment (mrclay) [inline engine/classes/Elgg/ActionsService.php]: But we'd still send the response?

Comment (mrclay) [inline engine/classes/Elgg/ActionsService.php]: I guess it doesn't matter either way.

**Comment by mrclay** [comment]
"an error" instead of "and error". This seems safe to me as successful handlers shouldn't forward with errors as the reason.

**Comment by mrclay** [comment]
> elgg.ajax should be able to interpret it as an error, and lightbox will fail silently.

Did you actually test this?

File: engine/classes/Elgg/ActionsService.php (hunk 1 above)
Comment (hypeJunction) [inline engine/classes/Elgg/ActionsService.php]: I don't think it matters. I suppose sending it would allow someone to parse JSON from response body, if they must.

**Comment by hypeJunction** [comment]
`elgg.ajax` displays a generic AJAX error message.

**Comment by mrclay** [comment]
LGTM, @juho-jaakkola what you think?

**Comment by hypeJunction** [comment]
If there is another LGTM I will resubmit without whitespace noise, and http codes should be a constant in one of the servicea., or better yet a method that calls a hook.

**Comment by juho-jaakkola** [comment]
LGTM

**Comment by mrclay** [comment]
Just remove the whitespace noise for 1.12. We don't really want refactoring there.

**Comment by hypeJunction** [comment]
@mrclay Exactly what I was thinking. Done.
