### PR TITLE
fix(comments): unifies behavior after adding new comment/discussion reply

### LINKED ISSUE #8130: Forward to comment after posting it
Currently user is taken by default to the commented object after posting a comment:
```php
forward(REFERER);
```

Couldn't we just always forward to the comment itself:
https://github.com/Elgg/Elgg/blob/master/actions/comment/save.php#L95

### PR DESCRIPTION
**Pull request by mrclay**
We forward to either the comment/reply URL or to the activity page if it was posted from there.

If returning to the activity page, the new comment/reply is jumped to and highlighted as it would be on the object/topic page.

Fixes #8130
- [x] remove `BC with 1.x:` from comments

### CODE REVIEW

**Comment by mrclay** [comment]
Referrer matching code is ugly but I'm working on an API to clean up. Might not make 2.1.

File: actions/comment/save.php [hunk 1]
```diff
@@ -100,8 +99,13 @@
...
 }
 
-if ($is_edit_page) {
-	forward($comment->getURL());
+// BC with 1.x: return to activity page if posted from there
+if (!empty($_SERVER['HTTP_REFERER'])) {
+	// don't redirect to URLs from client without verifying within site
+	$site_url = preg_quote(elgg_get_site_url(), '~');
+	if (preg_match("~^{$site_url}activity(/|\\z)~", $_SERVER['HTTP_REFERER'], $m)) {
+		forward("{$m[0]}#elgg-object-{$comment->guid}");
```
Comment (mrclay) [inline actions/comment/save.php]: Might be nice to allow passing in a context to getUrl that gets passed to the hook handlers. In this case we'd do `getUrl('activity')`. We don't want to alter the url handlers here because it would alter URLs in notifications.

**Comment by juho-jaakkola** [comment]
LGTM

File: actions/comment/save.php [hunk 2]
```diff
@@ -100,8 +99,13 @@
 	system_message(elgg_echo('generic_comment:posted'));
 }
 
-if ($is_edit_page) {
-	forward($comment->getURL());
+// BC with 1.x: return to activity page if posted from there
```
Comment (juho-jaakkola) [inline actions/comment/save.php]: BC with 1.x? What's the difference with 2.0?

Comment (mrclay) [inline actions/comment/save.php]: I might've been confused. I'll just remove that part.

File: actions/comment/save.php (hunk 1 above)
Comment (hypeJunction) [inline actions/comment/save.php]: Reminds me of https://github.com/Elgg/Elgg/issues/6634
