### PR TITLE
fix(messageboard): correctly register deletePost on ajax created posts

### LINKED ISSUE #4366: message board: new message board posts result in page reload (Trac #4366)
_Original ticket http://trac.elgg.org/ticket/4366 on 42114919-12-12 by trac user pjotr, assigned to unknown._

Elgg version: 1.8.3

elgg.messageboard.deletePost will not remove the annotation li element, but will remove the li holding the remove button, thus:
 * this line: $(link).closest('li').remove();
 * should be: $(link).parents('li[id^="item-annotation-"]').remove();
Either that or something similar. This one would remove the li holding the annotation itself.

The other problem is that elgg.messageboard.submit method will not unbind the default click event and confirmation for the newly added annotation. Thus, it would have a different confirmation message and would make a page refresh.

The fix could be running the procedure from elgg.messageboard.init method again (on all elements) or just do the same thing for the newly added one. There does not seem to be a huge difference about it.

### PR DESCRIPTION
**Pull request by jdalsem**
fixes #4366

### CODE REVIEW

File: mod/messageboard/views/default/messageboard/js.php [hunk 1]
```diff
@@ -37,20 +38,18 @@
...
 
-elgg.messageboard.deletePost = function(e) {
-	var link = $(this);
+elgg.messageboard.deletePost = function(elem) {
+	var link = $(elem);
 	var confirmText = link.attr('title') || elgg.echo('question:areyousure');
 
 	if (confirm(confirmText)) {
-		elgg.action($(this).attr('href'), {
+		elgg.action($(link).attr('href'), {
```
Comment (mrclay) [inline mod/messageboard/views/default/messageboard/js.php]: This looks double-jQuery wrapped

Comment (mrclay) [inline mod/messageboard/views/default/messageboard/js.php]: Let's just have $link as the argument.
