### PR TITLE
fix(core): make accesscollection save and rename work like documented

### LINKED ISSUE #12559: check AccessCollections->rename() use
scrutinizer https://scrutinizer-ci.com/g/Elgg/Elgg/issues/3.0/files/engine/classes/Elgg/Database/AccessCollections.php?selectedSeverities%5B0%5D=10&orderField=path&order=asc&fileId=engine/classes/Elgg/Database.php&honorSelectedPaths=0

https://github.com/Elgg/Elgg/blob/0f920398c776301badb404f4cb3984d3542f4caf/engine/classes/Elgg/Database/AccessCollections.php#L485-L504

### PR DESCRIPTION
**Pull request by jdalsem**
fixes #12559

### CODE REVIEW

File: engine/classes/ElggAccessCollection.php [hunk 1]
```diff
@@ -114,9 +114,9 @@ public function getDisplayName() {
 	 */
 	public function save() {
 		if ($this->id > 0) {
-			return _elgg_services()->accessCollections->rename($this->id, $this->name);
+			return (bool) _elgg_services()->accessCollections->rename($this->id, $this->name);
```
Comment (jeabakker) [inline engine/classes/ElggAccessCollection.php]: this is not needed as you fixed that the function only returns `bool`

Comment (jeabakker) [reply engine/classes/ElggAccessCollection.php]: if you're scared that the function may someday return something else add a unit test to make sure it doesn't

**Review by jeabakker — APPROVED** [review]
