### PR TITLE
fix(entities): update attribute when assuming container_guid value

### LINKED ISSUE #8981: Container magic in ElggEntity::create()
In `ElggEntity::create()`, `$container_guid` is set to `$owner_guid` if `0`. However later, the code tries to get container entity using `$this->getContainerEntity()`, rather than using `get_entity($container_guid)`.

Not sure what's going on there, but I getting:
`ERROR: User 2 tried to create a (object, album_image), but the given container 2 could not be loaded.`

### PR DESCRIPTION
**Pull request by hypeJunction**
ElggEntity::create() assumes that container_guid equals to owner_guid when container_guid
is set to 0, but does so in introduced variables without propagating the changes in
attributes array. This results in discrepancies between ElggEntity::getContainerGUID()
and the value written to the database

Fixes #8981

### CODE REVIEW

File: engine/tests/ElggEntityTest.php [hunk 1]
```diff
@@ -355,4 +355,23 @@ public function testCanAnnotateDoesntCallSpecificThenGenericHookForEmptyString()
...
+
+		// If container_guid attribute is not updated with owner_guid attribute
+		// ElggEntity::getContainerEntity() would return false
+		// thus terminating save()
+		$this->assertTrue($object->save());
+
+		$this->assertEqual($user->guid, $object->getContainerGUID());
+
+		$user->delete();
+
```
Comment (mrclay) [inline engine/tests/ElggEntityTest.php]: Also delete $object.

Comment (hypeJunction) [inline engine/tests/ElggEntityTest.php]: Deleting a user deletes the object
