### PR TITLE
fix(pages): removes deprecated use of input/write_access view

### LINKED ISSUE #8327: Pages plugin - deprecated write_access
In Elgg 1.11.1 I get this warning when creating a top-level page:

WARNING: Deprecated in 1.11: The input/write_access view is deprecated. The pages plugin now uses the ['access:collections:write', 'user'] hook to alter options. Called from [#14] /home/devk/www/mod/pages/views/default/input/write_access.php:5<br /> -> [#13] /home/devk/www/engine/classes/Elgg/ViewsService.php:391

At least core should be free of deprecated messages :-)

### PR DESCRIPTION
**Pull request by mrclay**
Deprecation notices will only occur if a dev has extended forms/pages/edit or input/write_access

Fixes #8327

### CODE REVIEW

**Comment by hypeJunction** [comment]
LGTM

File: mod/pages/views/default/forms/pages/edit.php [hunk 1]
```diff
@@ -44,6 +44,10 @@
 			'entity' => ($name == 'parent_guid') ? $vars['entity'] : null,
 		);
 		if ($input_view === 'input/access' || $input_view === 'input/write_access') {
+
+			// we'll instead be using use the "purpose" argument of input/access
```
Comment (juho-jaakkola) [inline mod/pages/views/default/forms/pages/edit.php]: The comment is a bit weird

**Comment by mrclay** [comment]
This was reworked to not break BC with plugins that extend input/write_access.
