### PR TITLE
fix(events): All hook/event handlers are now weighted properly

### LINKED ISSUE #1378: register_plugin_hook priority isn't applied globally (Trac #1378)
_Original ticket http://trac.elgg.org/ticket/1378 on 39884583-04-02 by trac user twall, assigned to unknown._

Elgg version: 1.6

The priority passed in with register_plugin_hook only affects the hook's priority in relation to other hooks registered with the same hook/object type.  

To ensure a hook is run first, you must both specify a priority of '0' AND specify both the hook and entity type.  To ensure a hook is run last, you must specify a priority of 1000 and use 'all'/'all' as the hook/object type.  Using hook names and entity types other than what is appropriate, simply to affect the priority, is what makes me consider this a bug.

The following sets of hooks are executed in order:
'hook'/'type'
'all'/'type'
'hook'/'all'
'all'/'all'

It may not be possible to merge these sets after registration, since the original ordering information is no longer available.  However, executing as they do results in the wrong results for priority.

Specificly, my 'check_permissions'/'object' hook will always be overridden by the 'check_permissions'/'all' hook set up by someone else, regardless of priority.

### PR DESCRIPTION
**Pull request by mrclay**
`getOrderedHandlers()` now orders handlers first by the priority and then by the registration order. This also bumps the priority of “all” handlers in attempt to emulate the calling order before this change.

Fixes #1378

BREAKING CHANGE:
To ensure your handler is called last, you must give it the highest priority of all matching handlers. To ensure your handler is called first, you must give it the lowest priority of all matching handlers. Registering with the keyword “all” no longer has any effect on calling order.
- [x] consider raising priority of core stuff registered with `all` to compensate

### CODE REVIEW

File: engine/classes/Elgg/HooksRegistrationService.php [hunk 1]
```diff
@@ -14,7 +14,19 @@
  */
 abstract class HooksRegistrationService {
 
-	private $handlers = array();
+	const REG_KEY_PRIORITY = 0;
+	const REG_KEY_INDEX = 1;
+	const REG_KEY_HANDLER = 2;
```
Comment (ewinslow) [inline engine/classes/Elgg/HooksRegistrationService.php]: Prefer these to be strings instead of ints, but the fact that they're constants eases most of the readability pain, so not a huge deal.

**Comment by ewinslow** [comment]
LGTM

**Comment by juho-jaakkola** [comment]
I've never really used the ```all``` hooks much, but I agree that the previous behavior seems a bit confusing. Sounds very logical to me that priority should always the defining factor.

**Comment by mrclay** [comment]
Look at the events/hooks in the inspector. Lots of "all" stuff is registered at 500, so any plugin using the default 500 will now fire after the core wildcard handler. Effectively this will move a lot of wildcard handlers from end to start of call list.

I suggest we compensate by making the default priority 600 if "all" is given. Ie the argument $priority = null then sniff others to decide whether that's 500 or 600.

Otherwise I think think this has more serious BC implications than expected.

**Comment by mrclay** [comment]
This compensation would break the order of wildcard handlers given explicit priority of say 599 among wildcard handlers using implicit default.

Better option would be to manually bump the priority of all core "all" registrations and tell plugins to consider doing the same.

**Comment by juho-jaakkola** [comment]
+1 for manual configuration. I think also plugin devs will want to explicitly define the priority now that it's possible.

**Comment by mrclay** [comment]
Core handlers bumped, also mentioned in commit msg and upgrading guide.

File: engine/lib/access.php [hunk 2]
```diff
@@ -606,8 +606,8 @@ function access_test($hook, $type, $value, $params) {
 	$events->registerHandler('ready', 'system', 'access_init');
 
 	// For overrided permissions
-	$hooks->registerHandler('permissions_check', 'all', 'elgg_override_permissions');
-	$hooks->registerHandler('container_permissions_check', 'all', 'elgg_override_permissions');
+	$hooks->registerHandler('permissions_check', 'all', 'elgg_override_permissions', 600);
```
Comment (mrclay) [inline engine/lib/access.php]: Handlers with one "all" got bumped to 600. Both "all"s got 700.

**Comment by juho-jaakkola** [comment]
Changes look good. @beck24 what do you think?

**Comment by ewinslow** [comment]
I this just waiting on @beck24 at this point?

**Comment by mrclay** [comment]
...or maybe another core member? Or we can just merge it.

**Comment by ewinslow** [comment]
I'd just do it. 3 sets of eyes is pretty good, and it's been open for almost 2 weeks..
