### PR TITLE
breaks(core): move exceptions to own namespace

### LINKED ISSUE #13026: remove unused exceptions

### PR DESCRIPTION
**Pull request by jeabakker**
fixes #13026

### CODE REVIEW

File: engine/lib/output.php [hunk 1]
```diff
@@ -428,7 +428,7 @@ function _elgg_sane_validate_url($url) {
 		return $res;
 	}
 
-	// Replace wide chars by “X”.
+	// Replace wide chars by â€œXâ€�.
```
Comment (jdalsem) [inline engine/lib/output.php]: uh

**Review by jdalsem — CHANGES_REQUESTED** [review]

**Review by jdalsem — APPROVED** [review]
