### PR TITLE
fix(db): correctly default subtypes to prevent PHP warning

### LINKED ISSUE #11817: 2.3: annoying warning about countable
get rid of
"count(): Parameter must be an array or an object that implements Countable" in file D:\htdocs\core23\engine\classes\Elgg\Database\EntityTable.php (line 934)

### PR DESCRIPTION
**Pull request by jeabakker**
fixes #11817

### CODE REVIEW

File: engine/classes/Elgg/Database/EntityTable.php [hunk 1]
```diff
@@ -911,7 +911,7 @@ public function getEntityTypeSubtypeWhereSql($table, $types, $subtypes, $pairs)
 				$types = array($types);
 			}
 
-			if ($subtypes && !is_array($subtypes)) {
+			if (!is_array($subtypes)) {
```
Comment (hypeJunction) [inline engine/classes/Elgg/Database/EntityTable.php]: There is no typehint so it could be false or null, not sure how normalisation works then. Maybe add a test to be sure

Comment (jeabakker) [reply engine/classes/Elgg/Database/EntityTable.php]: `null`, `''`, `0` are handled a bit later on https://github.com/Elgg/Elgg/blob/2.3/engine/classes/Elgg/Database/EntityTable.php#L950-L957
