### PR TITLE
fix(zaudio): Convert zaudio JS to AMD modules

### LINKED ISSUE #8283: Defer the inline zaudio scripts

### PR DESCRIPTION
**Pull request by mrclay**
Fixes #8283

@ewinslow this might be a simple example of conversion to AMD.

### CODE REVIEW

**Comment by hypeJunction** [comment]
A bit odd to iterate unique from time, but LGTM.

File: mod/zaudio/start.php [hunk 1]
```diff
@@ -13,6 +13,12 @@
 function zaudio_init() {
 	elgg_extend_view('css/elgg', 'zaudio/css');
 
+	elgg_define_js('elgg/zaudio/AudioPlayer', [
```
Comment (ewinslow) [inline mod/zaudio/start.php]: This probably shouldn't be prefixed with elgg. It's a third party lib. We don't do elgg/jquery for example

Comment (mrclay) [inline mod/zaudio/start.php]: Yeah, and the lib is going to be dropped into global space no matter what.
