### PR TITLE
Autogenerate password option in Add new user form

### LINKED ISSUE #9808: elgg_view_input() needs exceptions
Needs to add exceptions for:

- [x] `input/checkbox` - customize label rendering

### PR DESCRIPTION
**Pull request by hypeJunction**
**feature(forms): input/checkbox is now usable with elgg_view_input()**

Adds an exception to `elgg_view_input()` to render the label next to the checkbox input rather than above the input (as in other input types).
Adds default class for single checkbox inputs wrapped in an html tag with a label (`.elgg-input-single-checkbox`)
Adds an option to customize the HTML tag used to wrap the single checkbox input with a label
to avoid double wrapping with a `<label>` tag.

Fixes #9808

**chore(forms): update Add new user form to use elgg_view_input()**

Updates the admin Add new user form to use new elgg_view_input() API

**feature(forms): Add new user now has an option to autogenerate the password**

Makes it easier for admins to add new users by adding an option to autogenerate passwords.

### CODE REVIEW

**Comment by hypeJunction** [comment]
It always bugs me that I have to come up with a password for the user, which usually ends up being `123456`. This makes it easier to avoid having to think of a strong new password.

File: views/default/forms/useradd.php [hunk 1]
```diff
@@ -18,67 +20,66 @@
...
+
+echo elgg_view_input('email', [
+	'name' => 'email',
+	'value' => $email,
+	'label' => elgg_echo('email'),
+	'required' => true,
+]);
+
+// Not using sticky value to make JS implementation cleaner
+echo elgg_view_input('checkboxes', array(
```
Comment (mrclay) [inline views/default/forms/useradd.php]: Why not checkbox?

Comment (hypeJunction) [inline views/default/forms/useradd.php]: Because https://github.com/Elgg/Elgg/issues/9808

Comment (hypeJunction) [inline views/default/forms/useradd.php]: I will just add that exception while at it.

**Comment by hypeJunction** [comment]
Added the commit to render `checkbox` input nicely with `elgg_view_input()`

File: views/default/forms/useradd.php [hunk 2]
```diff
@@ -23,62 +25,58 @@
...
+	'label' => elgg_echo('email'),
+	'required' => true,
+]);
+
+echo elgg_view_input('checkbox', array(
+	'name' => 'autogen_password',
+	'value' => 1,
+	'default' => false,
+	'label' => elgg_echo('autogen_password_option'),
+	'checked' => false, // not using sticky value to make JS implementation cleaner
```
Comment (mrclay) [inline views/default/forms/useradd.php]: I guess you want this comment on the "default" key?

File: actions/useradd.php [hunk 3]
```diff
@@ -24,6 +24,15 @@
 	$admin = $admin[0];
 }
 
+$autogen_password = get_input('autogen_password');
+if (is_array($autogen_password)) {
```
Comment (mrclay) [inline actions/useradd.php]: Can get rid of this check now.

File: views/default/forms/useradd.php (hunk 2 above)
Comment (mrclay) [inline views/default/forms/useradd.php]: Actually you don't need to set default, because the hidden input can't emit a change event anyway

Comment (hypeJunction) [inline views/default/forms/useradd.php]: I mean if we add hidden class right away, we need to add boilerplate JS for
toggling classes/required attributes etc

File: actions/useradd.php (hunk 3 above)
Comment (hypeJunction) [inline actions/useradd.php]: Keeping it in the action for BC. Plugins may have overwritten the form.

Comment (hypeJunction) [inline actions/useradd.php]: Ah, never mind, this is the new input. Will do.

**Comment by hypeJunction** [comment]
This now supports sticky values for autogen_password input.

File: views/default/forms/useradd.php (hunk 2 above)
Comment (hypeJunction) [inline views/default/forms/useradd.php]: We don't need default values on these inputs.

**Comment by mrclay** [comment]
LGTM, can we get a 2nd?

**Comment by hypeJunction** [comment]
I want to get this into 2.2 (attempting a release now), and no one has time to review, so merging.
