### PR TITLE
fix(plugins): position and required state of plugins are now asserted

### LINKED ISSUE #13520: plugin position requirement is not enforced

### PR DESCRIPTION
**Pull request by jdalsem**
fixes #13520

### CODE REVIEW

File: engine/classes/ElggPlugin.php [hunk 1]
```diff
@@ -1457,6 +1457,45 @@ public function assertDependencies(): void {
...
+	 * @throws \Elgg\Exceptions\PluginException
+	 *
+	 * @since 4.0
+	 */
+	protected function assertPluginDependencies(): void {
+		foreach ($this->getDependencies() as $plugin_id => $plugin_dep) {
+			$must_be_active = elgg_extract('must_be_active', $plugin_dep, true);
+			$position = elgg_extract('position', $plugin_dep);
+
+			$dependent_plugin = elgg_get_plugin_from_id($plugin_id);
```
Comment (jeabakker) [inline engine/classes/ElggPlugin.php:1476]: are you sure this is a plugin? What if the required plugin isn't installed?

**Review by jeabakker — CHANGES_REQUESTED** [review]

**Review by jeabakker — APPROVED** [review]
