### PR TITLE
fix(database): prevent unwanted duplicate metadata records

### LINKED ISSUE #14740: reconsider entity setmetadata logic
Currently we do not update metadata (when using Entity->setMetadata which is the common usecase via the magic setter) but, on update, (optionally) delete the records before inserting a new record with the new value. We only delete metadata records if there is existing metadata. We use cached metadata to validate if there are metadata records. This causes issues for longer running processes (like cron jobs) that create a cache early, but check, when updating, later. It opens up a chance for a racing condition if other processes update the same entity. This can result in duplicate records where you do not expect them.

A solution could be to (instead of delete) actually update metadata record value, or by not using the cache to check for existing metadata, but validate in the database... both approaches have their own challenges

### PR DESCRIPTION
**Pull request by jdalsem**
fixes #14740

### CODE REVIEW

File: engine/classes/Elgg/Traits/Entity/Metadata.php [hunk 1]
```diff
@@ -76,53 +76,58 @@ public function getAllMetadata(): array {
...
 			// unsaved entity. store in temp array
 			return $this->setTempMetadata($name, $value, $multiple);
 		}
 		
 		// saved entity. persist md to db.
+		// disable metadatacache to always check the database to prevent racing conditions
+		$md_cache = _elgg_services()->metadataCache;
+		$md_cache_enabled = $md_cache->isEnabled();
+		$md_cache->disable();
+		$restore_md_cache = function() use ($md_cache, $md_cache_enabled){
```
Comment (jeabakker) [inline engine/classes/Elgg/Traits/Entity/Metadata.php:108]: how come the coding style don't detect the missing trailing space `) {`

**Review by jeabakker — CHANGES_REQUESTED** [review]

**Review by jeabakker — APPROVED** [review]
