### PR TITLE
fix(ckeditor): fixes basepath issues on some systems

### LINKED ISSUE #10724: Elgg 2.3.0: CKeditor broken (either issue in AMD module of CKeditor or Elgg core caching issue)
After denying in https://elgg.org/discussion/view/2594751/ckeditor-issue that CKeditor is broken I now also have a broken CKeditor on any browser with Elgg 2.3.0 and caching enabled.

Browser console gives me

> Failed to load resource: http://site.url/cache/1485283855/default/elgg/ckeditor/config.js
> the server responded with a status of 404 (Not Found)

and

> require.js:17 Uncaught Error: Script error for "elgg/ckeditor/config", needed by: elgg/ckeditor
> http://requirejs.org/docs/errors.html#scripterror
>     at makeError (require.js:17)
>     at HTMLScriptElement.onScriptError (require.js:117)

CKeditor instance loads fine with caching disabled or with at least no "cache" link in the root directory.

So, it might not be an issue of CKeditor but rather a bug with caching / cache rebuilding (maybe a problem connected or in addition of https://github.com/Elgg/Elgg/issues/10706)

### PR DESCRIPTION
**Pull request by mrclay**
As the CKeditor library is not a real AMD library, its execution may not be controlled as well by RequireJS, causing a race condition with the module that sets the global `CKEDITOR_BASEPATH` constant.

This renames the module `elgg/ckeditor` to `elgg-ckeditor` which eliminates the need for setting `CKEDITOR_BASEPATH` at all. With the new filename, the CKeditor library is no longer confused when sniffing for its resources folder.

Fixes #10724

BREAKING CHANGES:
The AMD module `elgg/ckeditor` is now `elgg-ckeditor`. The module `elgg/ckeditor/set-basepath` was removed.

### CODE REVIEW

File: mod/ckeditor/views/default/elgg-ckeditor.js [hunk 1]
```diff
@@ -17,48 +18,44 @@ define(function (require) {
...
-				editor_config = default_config;
-			}
+		bind: function (selector, config_module) {
+			config_module = config_module || DEFAULT_CONFIG_MODULE;
 
-			require([editor_config], function(config) {
-				elggCKEditor.config = config;
-				
+			require([config_module], function (config) {
 				elggCKEditor.registerHandlers();
```
Comment (mrclay) [inline mod/ckeditor/views/default/elgg-ckeditor.js]: @jdalsem I got rid of `elggCKEditor.config` here, as it isn't needed AFAICT.
