### PR TITLE
fix(session): Session is again available in the shutdown event

### LINKED ISSUE #9243: $_SESSION not available in shutdown:system event
The session is closed before this event is called, this can cause problems for events which rely on $_SESSION vars.

I thinks it's cause by https://github.com/symfony/symfony/blob/master/src/Symfony/Component/HttpFoundation/Session/Storage/NativeSessionStorage.php#L103, which registers a shutdown function to close the session. Since it's probably one of the first shutdown functions being registered it's called first.

This problem was introduced in Elgg 1.10 with the switch to Symfony Session managment

### PR DESCRIPTION
**Pull request by mrclay**
Fixes #9243

(when merging into 2.0 the shutdown registration should move to `\Elgg\Application::create`)

### CODE REVIEW

File: engine/start.php [hunk 1]
```diff
@@ -24,6 +24,15 @@
 global $START_MICROTIME;
 $START_MICROTIME = microtime(true);
 
+// we need to register for shutdown before Symfony registers the session_write_close() function
+// https://github.com/Elgg/Elgg/issues/9243
+register_shutdown_function(function () {
+	// there are cases where this might not be defined so check first
```
Comment (juho-jaakkola) [inline engine/start.php]: What are the cases?

Comment (mrclay) [inline engine/start.php]: Later in start.php we have a couple opportunities to exit(). In 2.0 you can create an Application but never load the core (I think).

Comment (juho-jaakkola) [inline engine/start.php]: Let's mention those in the inline comment.

**Comment by mrclay** [comment]
Updated
