### PR TITLE
fix(plugins): avoid multiple executions of runtime logic in plugin files

### LINKED ISSUE #11946: Elgg 3: On plugins listing page elgg-plugin.php is included twice
Why??

I had a define in the `elgg-plugin.php` on the plugins list I got a warning, already defined.
Why is de file included twice, should only be once, correct?

### PR DESCRIPTION
**Pull request by hypeJunction**
Instead of including plugin files, require them once and cache the output,
in case the file is needed again. This avoid executing runtime logic on
multiple file includes, as well as eliminates potential problems with
multiple function/variable declaralations.

Fixes #11946

### CODE REVIEW

**Comment by hypeJunction** [comment]
Don't merge if it passes yet. I will figure out how to test it to avoid regression on the bug.

File: engine/classes/ElggPlugin.php [hunk 1]
```diff
@@ -871,7 +871,7 @@ protected function includeFile($filename) {
 		}
 
 		try {
-			$ret = Includer::includeFile($filepath);
+			$ret = Application::requireSetupFileOnce($filepath);
```
Comment (jeabakker) [inline engine/classes/ElggPlugin.php]: this will fail (without exception) and crash the system if the `$filepath` isn't present.

Comment (hypeJunction) [reply engine/classes/ElggPlugin.php]: Doesn't it check if filepath is readable above?

Comment (jeabakker) [reply engine/classes/ElggPlugin.php]: > Doesn't it check if filepath is readable above?

correct

**Comment by jdalsem** [comment]
this is done right?

**Comment by hypeJunction** [comment]
I suppose it is. I am not 100% keen on it, but it will do the job for now. There are probably cases, when you would want the runtime logic to execute on each request, but at least not with the current plugin setup.
