### PR TITLE
fix(caches): disable caches during flush and upgrade

### LINKED ISSUE #10616: Do not use autoload_cache during upgrade
During upgrade the class autoload_cache is used. This cache is used for the storage of custom classes (and their paths). If you move a class... and fix this in the registration in a upgradescript for example... you still will have issues during upgrade if these classes are used during the system events (like plugins boot or init) as the cache is not invalidated.... maybe we could never use systemcache during the upgrade run... to prevent these kind of issues

### LINKED ISSUE #11205: Cacheroot shouldn't default to root
I keep getting just files in /system_cache

### LINKED ISSUE #11940: Do not use caches during flush/upgrade
If any of the caches (mainly boot cache) goes stale and causes issues there is no way to recover without wiping files in the cacheroot

### PR DESCRIPTION
**Pull request by hypeJunction**
Disables caching during flush and upgrade operations.
Adds API to disable/enable all or individual caches.

Refs #11897
Fixes #11940
Fixes #10616
Fixes #11205

### CODE REVIEW

File: engine/lib/cache.php [hunk 1]
```diff
@@ -308,13 +308,67 @@ function _elgg_cache_init() {
...
 return function(\Elgg\EventsService $events, \Elgg\HooksRegistrationService $hooks) {
 	$events->registerHandler('ready', 'system', '_elgg_cache_init');
-	
-	// register plugin hooks for cache reset
-	$events->registerHandler('cache:flush', 'system', 'elgg_reset_system_cache');
-	$events->registerHandler('cache:flush', 'system', 'elgg_invalidate_simplecache');
+
+	$events->registerHandler('cache:flush:before', 'system', '_elgg_disable_caches');
+	$events->registerHandler('cache:flush', 'system', '_elgg_clear_caches');
+	$events->registerHandler('cache:flush:after', 'system', '_elgg_enable_caches');
```
Comment (jeabakker) [inline engine/lib/cache.php]: couldn't this cause potential problems? If (for some reason) I disabled a cache, then flush (all) the caches it gets enabled again. Not what i expected.

File: engine/lib/configuration.php [hunk 2]
```diff
@@ -54,7 +54,8 @@ function elgg_get_data_path() {
  * @return string
  */
 function elgg_get_cache_path() {
-	return _elgg_config()->cacheroot;
+	$path = _elgg_config()->cacheroot ? : elgg_get_data_path() . 'caches/';
```
Comment (jeabakker) [inline engine/lib/configuration.php]: isn't this handled by https://github.com/Elgg/Elgg/pull/11948/files#diff-153aabf87ced6eb965431e48cc8b99ebR749

Comment (hypeJunction) [reply engine/lib/configuration.php]: There are use cases when this could be called without the boot, e.g. tests

File: engine/lib/cache.php (hunk 1 above)
Comment (hypeJunction) [reply engine/lib/cache.php]: Just use the handlers directly then.

Comment (hypeJunction) [reply engine/lib/cache.php]: All caches are private API anyway, plugins have no business messing with them. System cache enabled/disabled is handled separately I think. We can just inject a black hole instead of a file cache if need be.
