### PR TITLE
fix(install): Set default timezone on installation

### LINKED ISSUE #8845: Date warning causes exception on install
>PHP Warning:  date(): It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected the timezone 'UTC' for now, but please set date.timezone to select your timezone.

During installation the error logging isn't controlled so this warning may be displayed and cause an exception:

>RuntimeException' with message 'Failed to start the session because headers have already been sent by "/var/www/html/engine/lib/elgglib.php" at line 935.

### PR DESCRIPTION
**Pull request by beck24**
Timezone is set to UTC for the duration of the installation before settings.php is created
Settings.php now contains date_default_timezone_set() with the selected timezone

Fixes #8845

### CODE REVIEW

**Comment by beck24** [comment]
This is failing because Travis doesn't create the settings.php with the timezone (not really sure how Travis installs offhand).  What do we need to do for this to work?

File: engine/classes/ElggInstaller.php [hunk 1]
```diff
@@ -356,6 +356,12 @@ protected function database($submissionVars) {
 				'value' => 'elgg_',
 				'required' => TRUE,
 				),
+			'timezone' => array(
+				'type' => 'dropdown',
+				'value' => 'UTC',
+				'options' => \DateTimeZone::listIdentifiers(),
+				'required' => TRUE
+			)
```
Comment (juho-jaakkola) [inline engine/classes/ElggInstaller.php]: I think this should be user specific instead of site specific setting. Servers should always use UTC to avoid trouble related to timezone differences, daylight saving time, etc.

Setting the target timezone directly is of of course sufficient for sites used only within single timezone, but still I'd prefer adding a proper user specific timezone support instead.

Comment (beck24) [inline engine/classes/ElggInstaller.php]: This doesn't prevent such user specific timezone support, this just sets the initial server default timezone that the site is operating in as required for php 5.5+.  I agree that most times people would want it standardized at UTC, which is why I made it the default, but left it configurable just in case (and even if they change it at installation time, as long as it stays consistent there should be no issues).  Take a look at the arck events plugin to see how we handle user defined timezones.  That is currently working even while having the default timezone set in the settings.php

Comment (juho-jaakkola) [inline engine/classes/ElggInstaller.php]: What about cases where two systems located in different timezones communicate with each other?

Comment (mrclay) [inline engine/classes/ElggInstaller.php]: time() still matches.

**Comment by juho-jaakkola** [comment]
The timezone needs to be added here: https://github.com/Elgg/Elgg/blob/2.0/install/cli/travis_installer.php#L25 for the tests.

**Comment by beck24** [comment]
Ah, thanks, I'll add that in later today

**Comment by beck24** [comment]
Tests are passing now, thanks @juho-jaakkola

**Comment by mrclay** [comment]
LGTM
