### PR TITLE
fix(widgets): check page owner canEdit in can_edit_widget_layout

### LINKED ISSUE #11951: widget layout should be editable if user can edit page owner

### PR DESCRIPTION
**Pull request by jdalsem**
fixes #11951

### CODE REVIEW

File: engine/classes/Elgg/WidgetsService.php [hunk 1]
```diff
@@ -143,18 +143,21 @@ public function canEditLayout($context, $user_guid = 0) {
...
-			$return = ($user->isAdmin() || (elgg_get_page_owner_guid() == $user->guid));
-		} else {
-			$return = false;
+		$page_owner = elgg_get_page_owner_entity();
+		$default = false;
+		
+		if ($page_owner) {
+			$default = $page_owner->canEdit($user_guid);
+		} elseif ($user) {
+			$default = $user->isAdmin();
```
Comment (jeabakker) [inline engine/classes/Elgg/WidgetsService.php]: More efficient
```php
if ($user->isAdmin()) {
     $default = true;
} elseif ($page_owner) {
     $default = $page_owner->canEdit($user->guid);
}

Comment (jdalsem) [reply engine/classes/Elgg/WidgetsService.php]: $user is not always available, so doing it this way
