### PR TITLE
fix(likes): count is updated after liking/unliking

### LINKED ISSUE #9100: Likes count doesn't update on like/unlike
Pretty sad we haven't fixed this yet. Can we do it in a BC way?

### PR DESCRIPTION
**Pull request by mrclay**
Also removes focus from the icon so its state is more apparent.

Fixes #9100

### CODE REVIEW

**Comment by mrclay** [comment]
If we really want this it could go in 1.12 as well.

File: mod/likes/views/default/likes/js.php [hunk 1]
```diff
@@ -24,4 +25,39 @@
 };
 
 elgg.register_hook_handler('getOptions', 'ui.popup', elgg.ui.likesPopupHandler);
-elgg.ui.registerTogglableMenuItems('likes', 'unlike');
\ No newline at end of file
+
```
Comment (mrclay) [inline mod/likes/views/default/likes/js.php]: I figure this is BC because it still works if this view has been overridden, it just won't get this bug fix.

File: mod/likes/views/default/likes/count.php [hunk 2]
```diff
@@ -8,26 +8,30 @@
...
-		'title' => elgg_echo('likes:see'),
-		'class' => 'elgg-lightbox elgg-non-link',
-		'href' => '#',
-		'data-colorbox-opts' => json_encode([
-			'maxHeight' => '85%',
-			'href' => elgg_normalize_url("ajax/view/likes/popup?guid=$guid") 
-		]),
-	);
-	echo elgg_view('output/url', $params);
+elgg_load_js('lightbox');
```
Comment (hypeJunction) [inline mod/likes/views/default/likes/count.php]: Grrrrr. Just saying ;) :dizzy_face:

File: mod/likes/views/default/likes/count.php [hunk 3]
```diff
@@ -8,26 +8,30 @@
...
+	$likes_string = elgg_echo('likes:userslikedthis', array($num_of_likes));
+}
+
+$class = 'elgg-lightbox elgg-non-link';
+if (!$num_of_likes) {
+	$class .= ' hidden';
 }
+
+$params = array(
+	'text' => $likes_string,
```
Comment (hypeJunction) [inline mod/likes/views/default/likes/count.php]: Indentation.

Comment (hypeJunction) [inline mod/likes/views/default/likes/count.php]: Never mind. Quirk in Chrome.

**Comment by hypeJunction** [comment]
LGTM, but not tested.
