### PR TITLE
fix(views): clean up of class attribute usage

### LINKED ISSUE #11468: page/components/list doesn't support array 'class' in $vars
when provided in elgg_list_entities => 'list_class'

### PR DESCRIPTION
**Pull request by mrclay**
Fixes #11468

### CODE REVIEW

File: engine/lib/elgglib.php [hunk 1]
```diff
@@ -1219,18 +1219,19 @@ function elgg_extract($key, $array, $default = null, $strict = true) {
...
- * @param string|string[] $existing Existing name(s)
+ * @param array           $array       Source array
+ * @param string|string[] $existing    Existing name(s)
+ * @param string          $extract_key Key to extract new classes from
  * @return string[]
  *
  * @since 2.3.0
  */
-function elgg_extract_class(array $array, $existing = []) {
+function elgg_extract_class(array $array, $existing = [], $extract_key = 'class') {
```
Comment (hypeJunction) [inline engine/lib/elgglib.php]: I just did this in my theme PR. Great minds ...

**Review by jeabakker — APPROVED** [review]

File: engine/lib/elgglib.php (hunk 1 above)
Comment (jdalsem) [reply engine/lib/elgglib.php]: pff
