### PR TITLE
fix(views): input/userpicker API more BC with 1.8 plugins

### LINKED ISSUE #6079: input/userpicker docs wrong
pre-selected user key used to be `value` (as says in docs), but now requires `values`. Fix is to allow it to accept either for BC and update doc to `values` since this is now a multi-user picker.

### PR DESCRIPTION
**Pull request by mrclay**
Fixes #6079

### CODE REVIEW

File: views/default/input/userpicker.php [hunk 1]
```diff
@@ -24,6 +24,12 @@
 $name = htmlspecialchars($name, ENT_QUOTES, 'UTF-8');
 
 $guids = (array)elgg_extract('values', $vars, array());
+if (!$guids) {
+	// BC with earlier 1.x
+	if (!empty($vars['value'])) {
+		$guids = (array)elgg_extract('value', $vars, array());
```
Comment (juho-jaakkola) [inline views/default/input/userpicker.php]: Should this emit a deprecation warning?

Comment (mrclay) [inline views/default/input/userpicker.php]: Yes!

**Comment by mrclay** [comment]
Added deprecation.
