### PR TITLE
fix(core): unset on ElggData will always use magic setter

### LINKED ISSUE #9213: ElggEntity::__unset and ArrayAccess implementations give too much access
`__unset` allows setting any attribute to `""`. Safer would be to call `$this->__set($name, null);`

The `offset*` methods inherited from ElggData also allow direct attribute access without the same protections as in `__set`/`__get`.

### PR DESCRIPTION
**Pull request by jdalsem**
This ensures setter logic is also applied when using unset.

fixes #9213

### CODE REVIEW

File: engine/classes/ElggData.php [hunk 1]
```diff
@@ -64,6 +64,20 @@ public function __isset($name) {
...
 
+	/**
+	 * Unset a property from metadata or attribute.
+	 *
+	 * @warning If you use this to unset an attribute, you must save the object!
+	 *
+	 * @param string $name The name of the attribute or metadata.
+	 *
+	 * @return void
+	 * @todo some attributes should be set to null or other default values
```
Comment (jeabakker) [inline engine/classes/ElggData.php]: still needed??

**Review by jeabakker — CHANGES_REQUESTED** [review]

File: engine/classes/ElggData.php (hunk 1 above)
Comment (jdalsem) [reply engine/classes/ElggData.php]: nope... removed it

**Review by jeabakker — APPROVED** [review]

**Comment by jeabakker** [comment]
merge conflicts!!?? can't merge yet
