### PR TITLE
fix(notification): Removes warning handling the email, system hook

### LINKED ISSUE #8333: Argument 2 passed to elgg_extract() must be of the type array, null given
Hello, 
I get this warning in Elgg engine :
 ```php
PHP WARNING:  (IRDT): "Argument 2 passed to elgg_extract() must be of the type array, null given, called in /var/www/elgg/engine/lib/comments.php on line 280 and defined" in file /var/www/elgg/engine/lib/elgglib.php (line 1246), referer: http://localhost/members/expert_request
```
Is it an important issue or not? Should it be fixed?
Thanks.

### PR DESCRIPTION
**Pull request by mrclay**
If a [email, system] hook handler returns a non-array before this handler, we now return early.

Fixes #8333

### CODE REVIEW

File: engine/lib/comments.php [hunk 1]
```diff
@@ -275,6 +275,10 @@ function _elgg_comments_permissions_override($hook, $type, $return, $params) {
  * @return array $returnvalue Modified mail parameters
  */
 function _elgg_comments_notification_email_subject($hook, $type, $returnvalue, $params) {
+	if (!is_array($returnvalue)) {
+		// another hook handler returned a non-array, let's not override it
+		return;
```
Comment (hypeJunction) [inline engine/lib/comments.php]: IMHO, should still return the $returnvalue to the pipeline, in case someone wants to do something with it

Comment (mrclay) [inline engine/lib/comments.php]: null doesn't change the hook value.

Comment (hypeJunction) [inline engine/lib/comments.php]: Cross fingers and hope that it doesn't change in the future ;)

Comment (mrclay) [inline engine/lib/comments.php]: Test added #8387
