### PR TITLE
fix(views): adds excerpt to comments and discussions in activity context

### LINKED ISSUE #5811: comments on river not passed through elgg_get_excerpt()
I'm seeing a very large image in a comment so they must not be going through elgg_get_excerpt

### PR DESCRIPTION
**Pull request by jdalsem**
fixes #5811

### CODE REVIEW

**Comment by mrclay** [comment]
LGTM

File: mod/groups/views/default/object/discussion_reply.php [hunk 1]
```diff
@@ -38,11 +38,19 @@
...
-	'value' => $reply->description,
-	'class' => 'elgg-inner',
-	'data-role' => 'discussion-reply-text',
-));
+if (elgg_in_context('activity')) {
+	$content = '<div class="elgg-output elgg-inner" data-role="comment-text">';
+	$content .= elgg_view('output/text', array(
+		'value' => elgg_get_excerpt($reply->description)
+	));
+	$content .= '</div>';
```
Comment (juho-jaakkola) [inline mod/groups/views/default/object/discussion_reply.php]: nitpick: I'd prefer having opening and closing tag on the same row for readability.
