### PR TITLE
fix(javascript): replaces calls to obsolete $.die() method with $.off()

### LINKED ISSUE #9309: Deprecated jQuery methods in elgg.ui.popup*
`elgg.ui.popupOpen` and `elgg.ui.popupClose` still use deprecated `$.die()` method, which breaks the JS since jQuery migrate support is no longer included by default.

### PR DESCRIPTION
**Pull request by juho-jaakkola**
Fixes #9309

### CODE REVIEW

File: js/lib/ui.js [hunk 1]
```diff
@@ -171,7 +171,7 @@ elgg.ui.popupClose = function(event) {
 			}
 		});
 
-		$('body').die('click', elgg.ui.popClose);
+		$(document).off('click', elgg.ui.popupClose);
```
Comment (juho-jaakkola) [inline js/lib/ui.js]: I also fixed the callback name.

**Comment by mrclay** [comment]
LGTM
