### PR TITLE
fix(admin): Allow plugins to extend js/admin but deprecate it

### LINKED ISSUE #9238: 2.0 undocumented migrate action when extending js/admin
It is still possible to extend js/elgg, but this does not apply to js/admin anymore. Was this intended? If so, we need it documented somewhere. This is probably intended to get plugin devs to use AMD, but extending js/admin is very common, so explicit documentation about this change is appreciated.

### PR DESCRIPTION
**Pull request by mrclay**
The view js/admin was replaced in 2.0 but this was never mentioned in the plugin upgrade guide. We're supporting it for better BC.

Fixes #9238

### CODE REVIEW

**Comment by mrclay** [comment]
Pros: Allow more plugins to work, no real added cost to support
Cons: Allows more crusty JS practices to stick around.

**Comment by hypeJunction** [comment]
IMO, shady js practices will live no matter what.

**Comment by mrclay** [comment]
@hypeJunction is that a :+1: or :-1: on bringing it back?

**Comment by hypeJunction** [comment]
I don't have a strong inclination either way. As you say, it doesn't cost us much to support it, so let's bring it back. There is plenty of "crust" to get rid off before 3.x, and one extra file doesn't make a difference, especially if it helps some devs.

File: engine/lib/admin.php [hunk 1]
```diff
@@ -243,6 +258,11 @@ function _elgg_admin_init() {
 	elgg_register_action('profile/fields/reorder', '', 'admin');
 
 	elgg_register_simplecache_view('admin.css');
+
+	// deprecated
+	elgg_register_js('elgg.admin', elgg_get_simplecache_url('admin.js'));
+	elgg_register_plugin_hook_handler('view', 'admin.js', '_elgg_admin_deprecate_js_admin', 1000);
```
Comment (hypeJunction) [inline engine/lib/admin.php]: Any reason not to do it in the view itself?

File: views/default/admin.js.php [hunk 2]
```diff
@@ -0,0 +1,2 @@
+<?php
```
Comment (hypeJunction) [inline views/default/admin.js.php]: IMO, we don't need the actual file. If there are any extensions, they will be rendered despite, correct?

**Comment by hypeJunction** [comment]
I think we should either keep the hook or the view file. Not having the view file, might keep the devs away from extending it.

**Comment by jdalsem** [comment]
keep the hook... not the view. i agree with @hypeJunction that extending stuff should be discouraged

**Comment by mrclay** [comment]
Updated: View file no longer used, deprecation notice moved from /cache request to admin pages where more likely to be seen.

**Comment by hypeJunction** [comment]
LGTM
