### PR TITLE
fix(metadata): metadata values returned in more reliable order

### LINKED ISSUE #5603: Fetch metadata with order by id instead of time_created
This makes sure that values inserted during the same second are returned in order.

Looks like both elgg_get_metastring_based_objects() and the MD cache populateFromEntities() should be updated.

### PR DESCRIPTION
**Pull request by mrclay**
Storing multiple values often results in metadata rows with the same timestamp. Ordering by ID allows these values to be fetched in insertion order more reliably.

Fixes #5603

### CODE REVIEW

File: engine/classes/ElggVolatileMetadataCache.php [hunk 1]
```diff
@@ -289,7 +289,7 @@ public function populateFromEntities($guids) {
 				"JOIN {$db_prefix}metastrings n ON n_table.name_id = n.id",
 			),
 			'selects' => array('n.string AS name', 'v.string AS value'),
-			'order_by' => 'n_table.entity_guid, n_table.time_created ASC',
+			'order_by' => 'n_table.entity_guid, n_table.id ASC',
```
Comment (jdalsem) [inline engine/classes/ElggVolatileMetadataCache.php]: why not `n_table.time_created ASC, n_table.id ASC`? If you antidate the metadata this change could provide unexpected results

Comment (mrclay) [inline engine/classes/ElggVolatileMetadataCache.php]: You can alter neither the `id` nor the `time_created` columns via API. If you recreate the metadata, e.g., `$entity->foo = [1, 2]` you're going to get new rows anyway. If I'm missing something, what series of events are you worried about?

Comment (jdalsem) [inline engine/classes/ElggVolatileMetadataCache.php]: only custom queries can update time_created, but it "could" happen, and i believe there is no real downside in ordering by time created first and then by id, and it also solves your issue (= correct order for the same time_created)

**Comment by mrclay** [comment]
@jdalsem updated as you suggested
