### PR TITLE
chore(blog): Blog page resource view fixes and warning removals

### LINKED ISSUE #8556: master: "Undefined variable: page_type" in view resources/blog/all.php (line 7)

### PR DESCRIPTION
**Pull request by mrclay**
Fixes #8556

### CODE REVIEW

File: mod/blog/start.php [hunk 1]
```diff
@@ -102,50 +102,54 @@ function blog_page_handler($page) {
...
+		'page_type' => $page_type,
+	];
+
 	switch ($page_type) {
 		case 'owner':
-			set_input('username', $page[1]);
+			set_input('username', elgg_extract(1, $page));
 			
-			echo elgg_view_resource('blog/owner');
+			echo elgg_view_resource('blog/owner', $resource_vars);
```
Comment (ewinslow) [inline mod/blog/start.php]: Can you change it to just use `$vars` and drop all set_input calls?

Comment (mrclay) [inline mod/blog/start.php]: I don't have the patience for full refactoring at the moment.

Comment (jdalsem) [inline mod/blog/start.php]: we have #8569 for that
